import { notFound } from "next/navigation";
import { BookOpen, Brain, Languages, Users } from "lucide-react";
import { isLanguage } from "@/lib/site-content";
import { createPageMetadata, pageMetadataCopy } from "@/lib/metadata";

const copy = {
  ru: { title:"Обо мне и моих целях", lead:"Мне 46 лет, и я решила осуществить давнюю мечту — начать профессионально изучать психологию, которая интересовала меня с детства.", storyTitle:"Мой путь", story:["До этого я окончила коммерческую экономику в Hanzehogeschool и построила карьеру в международной компании CADMATIC, где занималась маркетингом и развитием судостроительного рынка в странах СНГ. Работа с людьми всегда побуждала меня задумываться о том, как мы мыслим, принимаем решения и реагируем на разные жизненные обстоятельства.","После приобретения дома в Испании моя жизнь стала проходить между Нидерландами и Испанией. Я начала изучать испанский язык, а затем приняла решение завершить прежний профессиональный этап и поступить на психологию в UNED.","Сегодня обучение для меня — не только путь к новой профессии, но и личное исследование. Мне интересно наблюдать, как взрослый человек осваивает сложную науку на неродном языке, как работают память и мотивация, как дислексия влияет на способы обучения и какую роль искусственный интеллект может играть в образовании.","Особое место в моих интересах занимает психобиология — изучение связи между мозгом, биологическими процессами, поведением и окружающей средой. Sensus Vitae появился как пространство, где я могу систематизировать полученные знания, проверять их по научным источникам и делиться ими с другими людьми."], goalsTitle:"Мои цели", goals:[["Учиться глубоко","Создавать целостную систему знаний по психологии, психобиологии и методам исследования."],["Объяснять ясно","Переводить сложные научные идеи на понятный язык, сохраняя точность и испанскую терминологию UNED."],["Развивать Sensus Vitae","Объединять студентов и любителей психологии в пространстве спокойного диалога, критического мышления и осознанной жизни."],["Идти к исследованию","Постепенно развиваться в психобиологии и поведенческой нейронауке и в будущем участвовать в научной работе."]], motto:"Знать · Думать · Развиваться · Жить осознанно" },
  es: { title:"Sobre mí y mis objetivos", lead:"Tengo 46 años y he decidido cumplir un sueño que me acompaña desde hace mucho tiempo: estudiar Psicología de manera profesional, una disciplina que me interesa desde la infancia.", storyTitle:"Mi camino", story:["Antes de emprender este camino, me gradué en Economía Comercial en la Hanzehogeschool y desarrollé mi carrera en la empresa internacional CADMATIC, donde trabajé en marketing y en el desarrollo del mercado de la construcción naval en los países de la CEI. Trabajar con personas siempre me ha llevado a preguntarme cómo pensamos, tomamos decisiones y reaccionamos ante distintas circunstancias de la vida.","Después de comprar una casa en España, mi vida comenzó a transcurrir entre los Países Bajos y España. Empecé a aprender español y, más tarde, decidí cerrar mi anterior etapa profesional para estudiar Psicología en la UNED.","Hoy, estudiar no es para mí únicamente un camino hacia una nueva profesión, sino también una investigación personal. Me interesa observar cómo una persona adulta aprende una ciencia compleja en una lengua que no es la suya, cómo funcionan la memoria y la motivación, cómo influye la dislexia en las formas de aprender y qué papel puede desempeñar la inteligencia artificial en la educación.","La psicobiología ocupa un lugar especial entre mis intereses: el estudio de la relación entre el cerebro, los procesos biológicos, la conducta y el entorno. Sensus Vitae nació como un espacio donde puedo organizar los conocimientos adquiridos, contrastarlos con fuentes científicas y compartirlos con otras personas."], goalsTitle:"Mis objetivos", goals:[["Aprender en profundidad","Construir un sistema coherente de conocimientos sobre psicología, psicobiología y métodos de investigación."],["Explicar con claridad","Traducir ideas científicas complejas a un lenguaje comprensible, conservando la precisión y la terminología de la UNED."],["Desarrollar Sensus Vitae","Reunir a estudiantes y amantes de la psicología en un espacio de diálogo sereno, pensamiento crítico y vida consciente."],["Avanzar hacia la investigación","Seguir formándome en psicobiología y neurociencia conductual para participar en el futuro en proyectos científicos."]], motto:"Saber · Pensar · Crecer · Vivir conscientemente" },
  en: { title:"About me and my goals", lead:"At 46, I decided to fulfil a long-held dream: to study psychology professionally, a subject that has interested me since childhood.", storyTitle:"My path", story:["Before taking this path, I graduated in Commercial Economics from Hanze University of Applied Sciences and built a career at the international company CADMATIC, working in marketing and shipbuilding market development across the CIS countries. Working with people has always prompted me to think about how we reason, make decisions and respond to different circumstances in life.","After buying a home in Spain, my life began to unfold between the Netherlands and Spain. I started learning Spanish and later decided to close the previous chapter of my professional life and study psychology at UNED.","Today, studying is not only a path towards a new profession, but also a personal investigation. I am interested in how an adult learns a complex science in a second language, how memory and motivation work, how dyslexia shapes ways of learning, and what role artificial intelligence can play in education.","Psychobiology holds a special place among my interests: the study of the connections between the brain, biological processes, behaviour and the environment. Sensus Vitae grew into a space where I can organise what I learn, examine it against scientific sources and share it with others."], goalsTitle:"My goals", goals:[["Learn deeply","Build a coherent system of knowledge across psychology, psychobiology and research methods."],["Explain clearly","Translate complex scientific ideas into accessible language while preserving accuracy and UNED terminology."],["Grow Sensus Vitae","Bring students and psychology enthusiasts together in a space for thoughtful dialogue, critical thinking and conscious living."],["Move towards research","Continue developing in psychobiology and behavioural neuroscience and, in time, contribute to scientific research."]], motto:"Know · Think · Grow · Live consciously" },
  nl: { title:"Over mij en mijn doelen", lead:"Op mijn 46e besloot ik een langgekoesterde droom waar te maken: psychologie professioneel gaan studeren, een vakgebied dat mij al sinds mijn jeugd interesseert.", storyTitle:"Mijn weg", story:["Voordat ik aan deze weg begon, studeerde ik Commerciële Economie aan de Hanzehogeschool en bouwde ik een carrière op bij het internationale bedrijf CADMATIC, waar ik werkte in marketing en marktontwikkeling voor de scheepsbouw in de GOS-landen. Het werken met mensen zette mij er altijd toe aan na te denken over hoe we denken, beslissingen nemen en reageren op verschillende levensomstandigheden.","Na de aankoop van een huis in Spanje ging mijn leven zich afspelen tussen Nederland en Spanje. Ik begon Spaans te leren en besloot later mijn vorige professionele hoofdstuk af te sluiten om psychologie aan de UNED te gaan studeren.","Studeren is voor mij nu niet alleen een weg naar een nieuw beroep, maar ook een persoonlijk onderzoek. Ik vind het interessant om te zien hoe een volwassene een complexe wetenschap in een andere taal leert, hoe geheugen en motivatie werken, hoe dyslexie invloed heeft op manieren van leren en welke rol kunstmatige intelligentie in het onderwijs kan spelen.","Psychobiologie neemt een bijzondere plaats in binnen mijn interesses: de studie van de samenhang tussen de hersenen, biologische processen, gedrag en de omgeving. Sensus Vitae is uitgegroeid tot een plek waar ik de opgedane kennis kan ordenen, aan wetenschappelijke bronnen kan toetsen en met anderen kan delen."], goalsTitle:"Mijn doelen", goals:[["Diep leren","Een samenhangend kennissysteem opbouwen rond psychologie, psychobiologie en onderzoeksmethoden."],["Helder uitleggen","Complexe wetenschappelijke ideeën toegankelijk maken met behoud van nauwkeurigheid en UNED-terminologie."],["Sensus Vitae ontwikkelen","Studenten en psychologieliefhebbers samenbrengen in een ruimte voor rustige dialoog, kritisch denken en bewust leven."],["Naar onderzoek toegroeien","Mij verder ontwikkelen in psychobiologie en gedragsneurowetenschappen en later bijdragen aan wetenschappelijk onderzoek."]], motto:"Weten · Denken · Groeien · Bewust leven" },
} as const;

const icons = [BookOpen, Languages, Users, Brain];

export async function generateMetadata({ params }: { params: Promise<{ lang: string }> }) {
  const { lang } = await params;
  if (!isLanguage(lang)) notFound();
  return createPageMetadata({ lang, path: "about", ...pageMetadataCopy.about[lang] });
}

export default async function AboutPage({ params }: { params: Promise<{ lang: string }> }) {
  const { lang } = await params;
  if (!isLanguage(lang)) notFound();
  const c = copy[lang];
  return <main className="mx-auto max-w-5xl px-5 py-14">
    <section className="paper-card rounded-[1.8rem] border bg-card p-7 sm:p-12">
      <p className="text-xs font-bold tracking-[.18em] text-[#98722e]">JEKATERINA IONOVA</p>
      <h1 className="font-editorial mt-4 max-w-3xl text-5xl font-bold leading-tight">{c.title}</h1>
      <div className="mt-7 grid gap-8 lg:grid-cols-[1fr_15rem] lg:items-start">
        <p className="border-l-2 border-[#b48a39] pl-5 text-xl leading-8 text-[#3f594d]">{c.lead}</p>
        <img src="/jekaterina-ionova.jpg" alt="Jekaterina Ionova" width="1080" height="1440" className="aspect-[3/4] w-full max-w-[15rem] rounded-[1.4rem] object-cover object-top shadow-[0_16px_45px_rgba(35,61,47,.12)]"/>
      </div>
      <div className="mt-12 grid gap-8 border-t pt-10 lg:grid-cols-[.72fr_1.28fr]"><div><h2 className="font-editorial text-3xl font-bold">{c.storyTitle}</h2></div><div className="space-y-5 text-lg leading-8 text-[#526359]">{c.story.map((p) => <p key={p}>{p}</p>)}</div></div>
    </section>
    <section className="py-14">
      <h2 className="font-editorial text-3xl font-bold">{c.goalsTitle}</h2>
      <div className="mt-7 grid gap-4 sm:grid-cols-2">{c.goals.map(([title, text], i) => { const Icon = icons[i]; return <article key={title} className="paper-card rounded-[1.4rem] border bg-[#fffdf8] p-6"><Icon size={22} className="text-[#a17a34]"/><h3 className="font-editorial mt-4 text-xl font-bold">{title}</h3><p className="mt-3 leading-7 text-[#5d6d64]">{text}</p></article>; })}</div>
    </section>
    <div className="rounded-[1.5rem] bg-[#173d30] p-7 text-[#f8f2e8] sm:p-9"><p className="font-editorial text-2xl font-bold sm:text-3xl">{c.motto}</p></div>
  </main>;
}
