export const chapterOneTranslations = {
  "es": [
    "Imagina que son las dos de la madrugada. Estás en la cama, cubierto de sudor pegajoso al pensar en el examen de mañana o en un informe importante. En ese momento, tu cerebro emprende un viaje sorprendente y cruel: del miedo a arruinar tu carrera pasa a la certeza de que tienes un tumor mortal que justifica tu pánico. Este es el mundo del estrés humano.",
    "Ahora trasladémonos a la sabana. Una cebra corre con todas sus fuerzas para no convertirse en la comida de un león, y el león corre igual de rápido para no morir de hambre. Para ellos, el estrés es una crisis física aguda que dura apenas unos minutos. Si la cebra escapa, su organismo vuelve inmediatamente al reposo.",
    "Esta es la gran tragedia humana descrita en el primer capítulo: nuestros cuerpos poseen un magnífico mecanismo de adaptación, diseñado para salvarnos en una breve carrera por la sabana. Sin embargo, al ser «lo bastante inteligentes», hemos aprendido a activar este potente sistema solo con el pensamiento, preocupándonos por la hipoteca o el estatus social.",
    "Si la homeostasis mantiene un nivel óptimo de oxígeno o temperatura, la alostasis es la compleja coordinación de todo el organismo para alcanzar el equilibrio. El problema es que hacemos saltar a los «elefantes del estrés» sobre el balancín de nuestro equilibrio interno con demasiada frecuencia.",
    "La cebra no sufre úlceras por anticipar un estrés con meses de antelación. El ser humano, en cambio, puede enfermar al activar su sistema de emergencia durante semanas o meses. La respuesta de estrés termina siendo más destructiva que el propio estresor.",
    "La historia científica de este capítulo aparece a través de los experimentos de Hans Selye, el «padre del estrés», quien, sin ser el más hábil en el laboratorio, perseguía a las ratas con una escoba. Observó que, independientemente del estímulo, el organismo producía una respuesta inespecífica similar: úlceras, aumento de las glándulas suprarrenales y atrofia del sistema inmunitario.",
    "La conclusión del capítulo: vivimos lo suficiente y con suficiente bienestar como para sufrir no solo infecciones o hambre, sino también enfermedades relacionadas con la preocupación crónica. Somos seres capaces de enfermarnos simplemente pensando en el futuro."
  ],
  "en": [
    "Imagine it is two in the morning. You are lying in bed, covered in clammy sweat as you think about tomorrow's exam or an important report. Your brain takes a remarkable and cruel journey: from the fear of ruining your career to the certainty that you have a deadly tumour that justifies your panic. This is the world of human stress.",
    "Now move to the savannah. A zebra runs as fast as it can to avoid becoming a lion's lunch, while the lion runs just as fast to avoid starvation. For them, stress is an acute physical crisis lasting only minutes. If the zebra escapes, its body immediately returns to rest.",
    "This is the central human tragedy described in the first chapter: our bodies have a magnificent adaptation mechanism designed to save our skin in a short race across the savannah. Yet, being ‘smart enough’, we have learned to activate this powerful system through thought alone, worrying about mortgages or social status.",
    "If homeostasis means maintaining an optimal oxygen level or temperature, allostasis is the complex coordination of the entire body to achieve balance. The problem is that we make the ‘elephants of stress’ jump onto the seesaw of our internal balance far too often.",
    "A zebra does not develop ulcers from anticipating stress months in advance. A human, however, can become ill by activating the emergency rescue system for weeks or months. The stress response eventually becomes more destructive than the stressor itself.",
    "The chapter's scientific history is told through the experiments of Hans Selye, the ‘father of stress’, who was not the most skilful laboratory worker and chased rats with a broom. He found that, regardless of the stimulus, the body produced a similar nonspecific response: ulcers, enlarged adrenal glands and atrophy of the immune system.",
    "The chapter's conclusion: we live long and comfortably enough to suffer not only from infection or hunger, but also from illnesses associated with chronic worry. We are creatures capable of making ourselves ill simply by thinking about the future."
  ],
  "nl": [
    "Stel je voor: het is twee uur 's nachts. Je ligt in bed, bedekt met klam zweet door gedachten aan het examen van morgen of een belangrijk rapport. Je hersenen maken een verbazingwekkende en wrede reis: van angst om je carrière te verpesten naar de zekerheid dat je een dodelijke tumor hebt die je paniek rechtvaardigt. Dit is de wereld van menselijke stress.",
    "Verplaats je nu naar de savanne. Een zebra rent zo hard mogelijk om niet de lunch van een leeuw te worden, en de leeuw rent even hard om niet van de honger te sterven. Voor hen is stress een acute lichamelijke crisis van slechts enkele minuten. Als de zebra ontsnapt, keert zijn lichaam onmiddellijk terug naar rust.",
    "Daarin schuilt de grote menselijke tragiek van het eerste hoofdstuk: ons lichaam heeft een prachtig aanpassingsmechanisme dat bedoeld is om ons te redden tijdens een korte sprint over de savanne. Maar doordat we ‘slim genoeg’ zijn, hebben we geleerd dit krachtige systeem alleen met gedachten te activeren, piekerend over de hypotheek of onze sociale status.",
    "Waar homeostase het handhaven van een optimaal zuurstofniveau of een optimale temperatuur betekent, is allostase de ingewikkelde coördinatie van het hele lichaam om evenwicht te bereiken. Het probleem is dat we de ‘stressolifanten’ veel te vaak op de wip van ons innerlijke evenwicht laten springen.",
    "Een zebra krijgt geen maagzweren doordat hij maanden van tevoren stress voorziet. Een mens kan juist ziek worden doordat hij het noodsysteem weken of maanden activeert. De stressreactie wordt uiteindelijk schadelijker dan de stressor zelf.",
    "De wetenschapsgeschiedenis in dit hoofdstuk wordt verteld via de experimenten van Hans Selye, de ‘vader van stress’, die niet de handigste laboratoriummedewerker was en ratten met een bezem achternazat. Hij ontdekte dat het lichaam ongeacht de prikkel een vergelijkbare, niet-specifieke reactie vertoonde: maagzweren, vergrote bijnieren en atrofie van het immuunsysteem.",
    "De conclusie van het hoofdstuk: we leven lang en welvarend genoeg om niet alleen aan infecties of honger te lijden, maar ook aan ziekten die samenhangen met chronisch piekeren. We zijn wezens die zichzelf ziek kunnen maken door alleen maar aan de toekomst te denken."
  ]
};

