export const clubContent = {
  ru: {
    title: "Клуб осознанной жизни",
    intro: "Клуб будет объединять чтение, размышления, обсуждения и короткие проверки знаний вокруг научных идей и важных вопросов жизни.",
    items: [
      ["Общее чтение и книги", "Первый проект совместного чтения клуба — Роберт Сапольски «Почему у зебр не бывает язв». Читаем по главам, разбираем ключевые идеи и используем вопросы для размышления и обсуждения."],
      ["Темы для обсуждения", "Вопросы по смыслу, морали, психологии, отношениям, привычкам и научному мышлению."],
      ["Автор дня", "Краткий взгляд на мыслителя, исследователя или автора, чьи идеи помогают глубже смотреть на темы клуба."],
      ["Термин дня", "Небольшие пояснения к ключевым понятиям, которые важны для понимания и дальнейшего чтения."],
      ["Вопрос дня", "Один размышляющий вопрос для ежедневного внимательного рассмотрения и обсуждения."],
      ["Встречи и активности", "Регулярные обсуждения, встречи и способы поддерживать живое сообщество вокруг обучения."],
      ["Самопроверка", "Короткие вопросы и мини-проверки, связанные с материалами клуба и темами чтения."],
    ],
    projectTitle: "Роберт Сапольски / Почему у зебр не бывает язв",
    authorName: "Роберт Сапольски",
    authorBlurb: "Психология и физиология стресса, научное мышление и глубокое чтение о том, как тело и мозг реагируют на давление.",
    authorImageAlt: "Портрет Роберта Сапольски",
    openLabel: "Открыть материал Сапольски",
    projectLabel: "Проект клуба",
    authorLabel: "Автор дня",
    photoLabel: "Фото",
  },
  es: {
    title: "Club para una vida consciente",
    intro: "El club reunirá lectura, reflexión, debate y breves comprobaciones de conocimiento en torno a ideas científicas y preguntas importantes sobre la vida.",
    items: [
      ["Lectura compartida y libros", "El primer proyecto de lectura conjunta del club es Robert Sapolsky «¿Por qué las cebras no tienen úlcera?». Leemos capítulo a capítulo, analizamos ideas clave y usamos preguntas para reflexionar y debatir."],
      ["Preguntas para debatir", "Cuestiones sobre significado, moral, psicología, relaciones, hábitos y pensamiento científico."],
      ["Autor del día", "Una mirada breve a un pensador o autor cuyas ideas ayudan a profundizar en los temas del club."],
      ["Término del día", "Explicaciones breves de conceptos clave para comprender mejor la lectura y el estudio."],
      ["Pregunta del día", "Una sola pregunta para reflexionar y discutir cada día con atención."],
      ["Encuentros y actividades", "Debates periódicos, encuentros y maneras de mantener una comunidad viva alrededor del aprendizaje."],
      ["Autoevaluación", "Preguntas cortas y mini-comprobaciones relacionadas con los materiales del club."],
    ],
    projectTitle: "Robert Sapolsky / ¿Por qué las cebras no tienen úlcera?",
    authorName: "Robert Sapolsky",
    authorBlurb: "Psicología y fisiología del estrés, pensamiento científico y lectura profunda sobre cómo el cuerpo y el cerebro responden a la presión.",
    authorImageAlt: "Retrato de Robert Sapolsky",
    openLabel: "Abrir material de Sapolsky",
    projectLabel: "Proyecto del club",
    authorLabel: "Autor del día",
    photoLabel: "Foto",
  },
  en: {
    title: "A club for conscious living",
    intro: "The club will bring together reading, reflection, discussion and short knowledge checks around scientific ideas and important questions in life.",
    items: [
      ["Shared reading and books", "The first joint reading project of the club is Robert Sapolsky’s Why Zebras Don’t Get Ulcers. We read chapter by chapter, unpack key ideas, and use reflection and discussion questions along the way."],
      ["Discussion prompts", "Questions on meaning, morality, psychology, relationships, habits and scientific thinking."],
      ["Author of the day", "A short look at a thinker or author whose ideas deepen the themes of the club."],
      ["Term of the day", "Brief explanations of key concepts for better understanding and further reading."],
      ["Question of the day", "One reflective question to consider and discuss each day."],
      ["Meetings and community activities", "Regular conversations, gatherings and ways to keep a living community around learning."],
      ["Self-check quizzes", "Short questions and mini-checks connected to club materials and reading themes."],
    ],
    projectTitle: "Robert Sapolsky / Why Zebras Don’t Get Ulcers",
    authorName: "Robert Sapolsky",
    authorBlurb: "The psychology and physiology of stress, scientific thinking and a deeper reading of how the body and brain respond to pressure.",
    authorImageAlt: "Portrait of Robert Sapolsky",
    openLabel: "Open Sapolsky material",
    projectLabel: "Club project",
    authorLabel: "Author of the day",
    photoLabel: "Photo",
  },
  nl: {
    title: "Club voor bewust leven",
    intro: "De club brengt samen lezen, reflectie, discussie en korte kennischecks rond wetenschappelijke ideeën en belangrijke levensvragen.",
    items: [
      ["Gezamenlijk lezen en boeken", "Het eerste gezamenlijke leesproject van de club is Robert Sapolsky’s Waarom krijgen zebra’s geen maagzweren? We lezen hoofdstuk voor hoofdstuk, bespreken de kernideeën en gebruiken vragen voor reflectie en gesprek."],
      ["Discussievragen", "Vragen over betekenis, moraal, psychologie, relaties, gewoonten en wetenschappelijk denken."],
      ["Auteur van de dag", "Een kort kijkje in de ideeën van een denker of auteur die de thema’s van de club verdiept."],
      ["Term van de dag", "Korte uitleg van kernbegrippen voor beter begrip en verder lezen."],
      ["Vraag van de dag", "Één reflectieve vraag om aandachtig te overdenken en te bespreken."],
      ["Vergaderingen en activiteiten", "Regelmatige gesprekken, bijeenkomsten en manieren om een levendige leercommunity te onderhouden."],
      ["Zelftoetsen", "Korte vragen en mini-checks gekoppeld aan clubmaterialen en leesonderwerpen."],
    ],
    projectTitle: "Robert Sapolsky / Waarom krijgen zebra’s geen maagzweren?",
    authorName: "Robert Sapolsky",
    authorBlurb: "De psychologie en fysiologie van stress, wetenschappelijk denken en een dieper inzicht in hoe lichaam en brein reageren op druk.",
    authorImageAlt: "Portret van Robert Sapolsky",
    openLabel: "Open Sapolsky-materiaal",
    projectLabel: "Clubproject",
    authorLabel: "Auteur van de dag",
    photoLabel: "Foto",
  },
} as const;
