import type { Language } from "./site-content";
// User-authored Google Docs summaries; standalone NotebookLM citation numbers omitted.
export const fullChapterSummaries: Record<Language, Record<number, string[]>> = {
  "en": {
    "2": [
      "Imagine sitting quietly in an armchair reading a book. Your body is still, but one vivid thought—an old hurt, a passionate date or an approaching deadline—makes your heart race and your palms grow damp. This is the magic of chapter two, revealing the hidden threads connecting our thoughts with every cell of our body.",
      "At the centre of this mechanism is the autonomic nervous system, divided into two eternal antagonists:",
      "* The sympathetic system is the ‘accelerator’. It instantly activates the fight-or-flight response, making hair stand on end and the blood surge with adrenaline.",
      "* The parasympathetic system is the ‘brake’. It handles rest, sleep, digestion and recovery.",
      "But nerves are merely fast messengers. Real power in the body belongs to hormones, and the sources have a story about the ‘great conductor’. Scientists long mistakenly considered the pituitary the ‘master gland’, but the dramatic rivalry between Roger Guillemin and Andrew Schally demonstrated that the true ruler is the hypothalamus. For years, these scientists processed tonnes of brains from slaughterhouses to find tiny amounts of the hormones through which the brain controls the body.",
      "When the alarm sounds, the body's orchestra changes its tune:",
      "1. The ‘soldiers’ are activated: the adrenal glands release adrenaline (acting over seconds) and glucocorticoids (sustaining the response for hours). The pituitary releases prolactin and vasopressin.",
      "2. ‘Peacetime construction’ stops: the body shuts down costly, long-term activities. Insulin levels fall (energy is spent rather than stored), while reproductive hormones (oestrogen, progesterone, testosterone) and growth hormone are suppressed.",
      "The sources emphasise that this storm is not always the same. Psychologist Shelley Taylor found that stress in women often triggers not aggression but ‘tend and befriend’, a mechanism aimed at strengthening social bonds.",
      "Chapter conclusion: our hormonal system is a finely crafted instrument designed to save lives in a brief struggle. But if we make it play an alarm march for months, without letting the ‘brake’ engage, the symphony turns into a requiem for our health."
    ],
    "3": [
      "Chapter three, ‘Stroke, Heart Attacks, and Voodoo Death’, examines how stress affects the cardiovascular system and why our response can become deadly.",
      "These are the chapter's main ideas:",
      "1. How the heart saves a life (the acute response)",
      "In a physical crisis, such as encountering a lion, the body immediately reorganises cardiovascular activity. To do this, the brain:",
      "* ‘Steps on the accelerator’: switches off the parasympathetic ‘brake’ and activates the sympathetic nervous system.",
      "* Speeds up the rhythm: the heart beats faster and harder.",
      "* Redistributes resources: arteries supplying working muscles widen, while blood flow to ‘secondary’ organs such as the intestines and skin falls sharply.",
      "* Sheds ballast: to lighten the body for running, the body seeks to empty the bladder.",
      "2. Chronic wear: when the ‘pump’ breaks",
      "The human problem is activating this powerful mechanism not only when facing a lion, but also during psychological distress, such as a son's untidy room or a deadline.",
      "* Hypertension: persistently high pressure wears down blood vessels. They become stiffer and thicker to withstand the force of blood, raising pressure further.",
      "* Atherosclerosis: inflammation develops where high pressure has damaged blood vessels. Fats, glucose and ‘bad’ cholesterol begin sticking to these ‘potholes’, forming atherosclerotic plaques.",
      "* C-reactive protein (CRP): Sapolsky notes that CRP levels, a marker of inflammation, predict heart disease much more accurately than cholesterol levels.",
      "3. Cardiovascular catastrophes",
      "Chronic stress prepares the ground for acute attacks:",
      "* Heart attack and stroke: under blood pressure, a plaque can detach and block a narrow vessel in the heart (heart attack) or brain (stroke).",
      "* Myocardial ischaemia: a healthy person's coronary vessels widen during stress, but in someone with disease they may paradoxically narrow, depriving the heart of oxygen when it is working at its limit.",
      "* Sudden death: extreme stress can cause a fatal rhythm disturbance, ventricular fibrillation, in which the heart quivers chaotically without pumping blood.",
      "4. Death from pleasure and ‘witchcraft’",
      "The author emphasises that, for the heart, it does not matter whether the body's storm comes from grief or ecstatic joy, such as an orgasm or a big win—the load is the same. The chapter also discusses ‘voodoo death’, or psychophysiological death: a phenomenon in which someone dies following extreme social or psychological shock, such as a curse. Sapolsky explains it through excessive sympathetic activation leading to cardiac arrest.",
      "Chapter conclusion",
      "The cardiovascular system is a ‘smart’ mechanism, ideally adapted to a short sprint across the savannah. Yet chronic activation for purely psychological reasons turns it into an instrument of slow self-destruction, leading to hypertension, blocked vessels and sudden catastrophes."
    ],
    "4": [
      "Chapter four, ‘Stress, Metabolism, and Liquidating Your Assets’, examines how the body manages energy reserves in a crisis and the price of constant ‘raids on the bank’.",
      "1. The metabolic bank: how we store energy",
      "Imagine your body as a complex financial system. After a substantial meal, while you rest on the sofa, your body accumulates ‘capital’. Simple ‘cash’—glucose, amino acids and fatty acids—is converted into complex ‘assets’:",
      "* Glycogen (stored in the liver and muscles);",
      "* Proteins (in muscles);",
      "* Triglycerides (in fat cells).",
      "The chief ‘banker’ managing these deposits and planning your metabolic future is insulin.",
      "2. The stress response: urgent liquidation of assets",
      "When a lion chases you, the body has no time for long-term investments. It must immediately turn accumulated property into ‘ready cash’—energy for the muscles.",
      "1. Deposits stop: the sympathetic nervous system switches off insulin, the ‘banker’. Glucocorticoids block nutrient delivery to storage.",
      "2. Assets are sold off: stress hormones—adrenaline, noradrenaline, glucagon and glucocorticoids—reverse the process, converting proteins, glycogen and fats back into amino acids, glucose and fatty acids and releasing them into the blood.",
      "3. Gluconeogenesis: the liver urgently converts even amino acids into glucose, the most readily available fuel for saving your skin.",
      "3. Why we become ill: the cost of chronic stress",
      "The modern human problem is ‘liquidating assets’ because of anxious thoughts rather than to escape a lion.",
      "* Chronic fatigue: constantly moving energy from storage into the blood and back is very costly. These manoeuvres consume so much energy that we tire more quickly.",
      "* Myopathy (muscle atrophy): during months of stress, muscles constantly break down proteins and cannot recover fast enough, leading to wasting.",
      "* Atherosclerosis: the tonnes of fat and glucose continually circulating because of stress eventually settle on damaged vessel walls, clogging them.",
      "4. Diabetes and metabolic syndrome",
      "The chapter explains the connection between stress and metabolic disorders:",
      "* Type 1 diabetes: stress can accelerate the appearance of symptoms and worsen blood sugar control.",
      "* Type 2 diabetes: this is a disease of insulin resistance. Persistent stress hormones tell cells to ignore insulin. Over time, a healthy person can develop diabetes.",
      "* Metabolic syndrome (syndrome X): Sapolsky describes a ‘whole bouquet’ of mutually reinforcing problems—blood pressure, obesity, high blood sugar and cholesterol.",
      "Chapter conclusion: chronic stress makes us constantly ‘withdraw money’ and keep it in the blood. Our metabolic banks empty (muscles atrophy), while blood vessels become clogged with this unused ‘rubbish’. We face allostatic load: bodily wear that can leave the body on the brink of catastrophe even when measured values remain formally normal."
    ]
  },
  "es": {
    "2": [
      "Imagina que estás sentado tranquilamente en un sillón leyendo un libro. Tu cuerpo está inmóvil, pero un pensamiento intenso —una antigua ofensa, una cita apasionada o una fecha límite próxima— acelera tu corazón y humedece tus palmas. Esta es la magia del segundo capítulo, que revela los hilos secretos que unen nuestros pensamientos con cada célula del cuerpo.",
      "En el centro de este mecanismo está el sistema nervioso autónomo, dividido en dos antagonistas eternos:",
      "* El sistema simpático es el «acelerador». Activa al instante la respuesta de lucha o huida, eriza el vello y hace que la sangre rebose adrenalina.",
      "* El sistema parasimpático es el «freno». Se ocupa del descanso, el sueño, la digestión y la recuperación.",
      "Pero los nervios solo son mensajeros rápidos. El verdadero poder pertenece a las hormonas, y las fuentes cuentan la historia del «gran director de orquesta». Durante mucho tiempo se consideró erróneamente que la hipófisis era la «glándula maestra», pero la dramática rivalidad científica entre Roger Guillemin y Andrew Schally demostró que el auténtico gobernante era el hipotálamo. Durante años, ambos procesaron toneladas de cerebros de mataderos para encontrar cantidades minúsculas de las hormonas con las que el cerebro controla el cuerpo.",
      "Cuando suena la alarma, la orquesta del organismo cambia de melodía:",
      "1. Se activan los «soldados»: las suprarrenales liberan adrenalina, que actúa en segundos, y glucocorticoides, que sostienen la respuesta durante horas. La hipófisis libera prolactina y vasopresina.",
      "2. Se detienen las «obras en tiempos de paz»: el organismo desactiva las actividades costosas y a largo plazo. Disminuye la insulina —la energía se gasta en lugar de almacenarse— y se suprimen las hormonas reproductivas (estrógeno, progesterona y testosterona) y la hormona del crecimiento.",
      "Sin embargo, las fuentes subrayan que esta tormenta no siempre es igual. La psicóloga Shelley Taylor observó que, en las mujeres, el estrés suele activar un mecanismo de «cuidar y entablar vínculos» en lugar de agresión, orientado a reforzar las relaciones sociales.",
      "Conclusión del capítulo: el sistema hormonal es un instrumento delicado, creado para salvar la vida en una lucha breve. Si lo obligamos a tocar una marcha de alarma durante meses sin permitir que actúe el «freno», la sinfonía se convierte en un réquiem por nuestra salud."
    ],
    "3": [
      "El tercer capítulo, «Ictus, infartos y muerte vudú», aborda cómo afecta el estrés al sistema cardiovascular y por qué nuestra respuesta puede volverse mortal.",
      "Estas son las principales ideas del capítulo:",
      "1. Cómo salva vidas el corazón (respuesta aguda)",
      "En una crisis física, por ejemplo al encontrarse con un león, el organismo reorganiza inmediatamente el sistema cardiovascular. Para ello, el cerebro:",
      "* «Pisa el acelerador»: desactiva el sistema parasimpático, el «freno», y activa el simpático.",
      "* Acelera el ritmo: el corazón late más rápido y con más fuerza.",
      "* Redistribuye recursos: se dilatan las arterias que abastecen a los músculos activos y cae drásticamente el riego de órganos «secundarios», como el intestino y la piel.",
      "* Suelta lastre: para aligerar el cuerpo al correr, el organismo intenta vaciar la vejiga.",
      "2. Desgaste crónico: cuando se avería la «bomba»",
      "El problema humano es que activamos este potente mecanismo no solo ante un león, sino también por preocupaciones psicológicas, como el desorden de la habitación de un hijo o una fecha límite.",
      "* Hipertensión: la presión elevada constante desgasta los vasos. Sus paredes se vuelven más rígidas y gruesas para soportar la fuerza de la sangre, lo que eleva aún más la presión.",
      "* Aterosclerosis: aparece inflamación donde la presión ha dañado los vasos. En esos «baches» empiezan a adherirse grasas, glucosa y colesterol «malo», formando placas ateroscleróticas.",
      "* Proteína C reactiva (PCR): Sapolsky señala que su nivel, un marcador de inflamación, predice las enfermedades cardíacas con mucha más precisión que el colesterol.",
      "3. Catástrofes cardiovasculares",
      "El estrés crónico prepara el terreno para episodios agudos:",
      "* Infarto e ictus: bajo la presión sanguínea, una placa puede desprenderse y obstruir un vaso estrecho del corazón (infarto) o del cerebro (ictus).",
      "* Isquemia miocárdica: en una persona sana, los vasos del corazón se dilatan con el estrés; en una persona enferma pueden estrecharse paradójicamente, privando al corazón de oxígeno justo cuando trabaja al límite.",
      "* Muerte súbita: un estrés extremo puede provocar una arritmia mortal, la fibrilación ventricular, en la que el corazón tiembla caóticamente sin bombear sangre.",
      "4. Muerte por placer y «brujería»",
      "El autor subraya que al corazón le da igual si la tormenta corporal procede del dolor o de una alegría extática, como un orgasmo o un gran premio: la carga es la misma. También examina la «muerte vudú», o muerte psicofisiológica: un fenómeno en el que una persona muere tras un choque social o psicológico extremo, como una maldición. Sapolsky lo explica por una activación simpática excesiva que conduce a una parada cardíaca.",
      "Conclusión del capítulo",
      "El sistema cardiovascular es un mecanismo «inteligente», perfectamente adaptado a un breve sprint por la sabana. Sin embargo, su activación crónica por motivos puramente psicológicos lo convierte en un instrumento de autodestrucción lenta, que conduce a hipertensión, obstrucción vascular y catástrofes repentinas."
    ],
    "4": [
      "El cuarto capítulo, «Estrés, metabolismo y liquidación de activos», explica cómo administra el organismo sus reservas de energía durante las crisis y qué precio pagamos por los constantes «asaltos al banco».",
      "1. El banco metabólico: cómo almacenamos energía",
      "Imagina tu cuerpo como un complejo sistema financiero. Después de comer abundantemente y descansar en el sofá, el organismo acumula «capital». El «efectivo» —glucosa, aminoácidos y ácidos grasos— se transforma en «activos» complejos:",
      "* Glucógeno (almacenado en hígado y músculos);",
      "* Proteínas (en los músculos);",
      "* Triglicéridos (en las células adiposas).",
      "La insulina es el principal «banquero» que administra estos depósitos y planifica el futuro metabólico.",
      "2. La respuesta de estrés: liquidación urgente de activos",
      "Cuando te persigue un león, el organismo no está para inversiones a largo plazo. Necesita convertir de inmediato su patrimonio en «dinero contante»: energía para los músculos.",
      "1. Se detienen los depósitos: el sistema simpático desactiva a la insulina, el «banquero». Los glucocorticoides bloquean la entrega de nutrientes a los almacenes.",
      "2. Se venden los bienes: las hormonas del estrés —adrenalina, noradrenalina, glucagón y glucocorticoides— invierten el proceso y convierten proteínas, glucógeno y grasas en aminoácidos, glucosa y ácidos grasos, liberándolos a la sangre.",
      "3. Gluconeogénesis: el hígado transforma de urgencia incluso los aminoácidos en glucosa, el combustible más accesible para salvar el pellejo.",
      "3. Por qué enfermamos: el precio del estrés crónico",
      "El problema moderno es que «liquidamos activos» por pensamientos ansiosos, no para escapar de un león.",
      "* Fatiga crónica: mover constantemente energía de los almacenes a la sangre y de vuelta resulta muy costoso. Gastamos tanto en estas maniobras que nos cansamos antes.",
      "* Miopatía (atrofia muscular): durante meses de estrés, los músculos descomponen continuamente proteínas sin poder recuperarse a tiempo, lo que provoca su desgaste.",
      "* Aterosclerosis: las toneladas de grasa y glucosa que circulan constantemente por el estrés terminan depositándose en las paredes vasculares dañadas y obstruyéndolas.",
      "4. Diabetes y síndrome metabólico",
      "El capítulo explica la relación entre el estrés y los trastornos metabólicos:",
      "* Diabetes tipo 1: el estrés puede acelerar la aparición de síntomas y empeorar el control de la glucemia.",
      "* Diabetes tipo 2: es una enfermedad de resistencia a la insulina. Las hormonas del estrés persistentes ordenan a las células ignorarla. Si esto se prolonga, una persona sana puede desarrollar diabetes.",
      "* Síndrome metabólico (síndrome X): Sapolsky lo describe como un «ramillete» de problemas —presión arterial, obesidad, glucemia y colesterol elevados— que se refuerzan mutuamente.",
      "Conclusión del capítulo: el estrés crónico nos hace «retirar dinero de la cuenta» constantemente y mantenerlo en la sangre. Los bancos metabólicos se vacían (los músculos se atrofian) y los vasos se obstruyen con esos «residuos» no utilizados. Nos enfrentamos a la carga alostática: un desgaste que puede situar al organismo al borde de la catástrofe incluso con valores formalmente normales."
    ]
  },
  "ru": {
    "2": [
      "Представьте, что вы спокойно сидите в кресле и читаете книгу. Ваше тело неподвижно, но одна яркая мысль — о старой обиде, страстном свидании или предстоящем дедлайне — заставляет ваше сердце биться чаще, а ладони покрываться влагой. Это магия второй главы, которая раскрывает тайные нити, связывающие наши мысли с каждой клеткой нашего тела.",
      "В центре этого механизма находится автономная нервная система, разделенная на двух вечных антагонистов:",
      "* Симпатическая система — это «педаль газа». Она мгновенно включает реакцию «нападай или убегай», заставляя волосы вставать дыбом, а кровь — бурлить адреналином.",
      "* Парасимпатическая система — это «тормоз». Она отвечает за покой, сон, пищеварение и восстановление сил.",
      "Но нервы — это лишь быстрые гонцы. Настоящая власть в теле принадлежит гормонам, и здесь источникам есть что рассказать о «великом дирижере». Долгое время ученые ошибочно считали «главной железой» гипофиз, но драматическая история научного соперничества Роже Гиймена и Эндрю Шалли доказала: истинный правитель — это гипоталамус. Эти двое ученых годами перерабатывали тонны мозгов со скотобоен, чтобы найти крошечные капли гормонов, которыми мозг управляет телом.",
      "Когда звучит сигнал тревоги, оркестр нашего организма меняет мелодию:",
      "1. Включаются «солдаты»: Надпочечники выбрасывают адреналин (действует секунды) и глюкокортикоиды (поддерживают реакцию часами). Гипофиз выделяет пролактин и вазопрессин.",
      "2. Замирают «мирные стройки»: Организм отключает всё дорогостоящее и долгосрочное. Снижается уровень инсулина (энергия больше не копится, а тратится), подавляются репродуктивные гормоны (эстроген, прогестерон, тестостерон) и гормон роста.",
      "Однако источники подчеркивают, что эта буря не всегда одинакова. Психолог Шелли Тейлор обнаружила, что у женщин стресс часто запускает не агрессию, а механизм «заботы и поддержки», направленный на укрепление социальных связей.",
      "Итог главы: Наша гормональная система — это филигранный инструмент, созданный для спасения жизни в короткой схватке. Но если мы заставляем этот инструмент играть марш тревоги месяцами напролет, не давая «тормозу» нажать на педаль, симфония превращается в реквием для нашего здоровья."
    ],
    "3": [
      "Третья глава книги, озаглавленная «Инсульт, сердечные приступы и смерть от колдовства», посвящена тому, как стресс влияет на работу сердечно-сосудистой системы и почему наша реакция на него может стать смертельно опасной.",
      "Вот основные идеи этой главы:",
      "1. Как сердце спасает жизнь (острая реакция)",
      "В момент физического кризиса (например, при встрече со львом) организм немедленно перестраивает работу сердечно-сосудистой системы. Для этого мозг:",
      "* «Нажимает на газ»: выключает парасимпатическую («тормоз») и включает симпатическую нервную систему.",
      "* Ускоряет ритм: сердце начинает биться быстрее и сильнее.",
      "* Перераспределяет ресурсы: артерии, ведущие к работающим мышцам, расширяются, а кровоснабжение «второстепенных» органов (кишечника, кожи) резко снижается.",
      "* Сбрасывает балласт: чтобы облегчить вес тела для бега, организм стремится опустошить мочевой пузырь.",
      "2. Хронический износ: когда «насос» ломается",
      "Проблема человека в том, что он активирует этот мощный механизм не только при встрече со львом, но и из-за психологических переживаний (например, из-за беспорядка в комнате сына или дедлайна).",
      "* Гипертония: постоянное повышенное давление изнашивает сосуды. Они становятся более жесткими и толстыми, чтобы выдерживать напор крови, что еще больше повышает давление.",
      "* Атеросклероз: в местах повреждения сосудов из-за высокого давления возникают воспаления. К этим «выбоинам» начинают прилипать жиры, глюкоза и «плохой» холестерин, формируя атеросклеротические бляшки.",
      "* С-реактивный белок (СРБ): Сапольски отмечает, что уровень СРБ (маркера воспаления) является гораздо более точным предсказателем болезней сердца, чем уровень холестерина.",
      "3. Сердечные катастрофы",
      "Хронический стресс готовит почву для острых приступов:",
      "* Инфаркт и инсульт: под давлением крови бляшка может оторваться и закупорить узкий сосуд в сердце (инфаркт) или мозге (инсульт).",
      "* Ишемия миокарда: у здорового человека при стрессе сосуды сердца расширяются, но у больного они могут парадоксально сужаться, лишая сердце кислорода именно тогда, когда оно работает на пределе.",
      "* Внезапная смерть: сильнейший стресс может вызвать фатальное нарушение ритма (фибрилляцию желудочков), когда сердце просто хаотично дрожит, не качая кровь.",
      "4. Смерть от удовольствия и «колдовства»",
      "Автор подчеркивает, что для сердца неважно, вызвана ли буря в организме горем или экстатической радостью (например, оргазмом или крупным выигрышем) — нагрузка на систему одинакова. Также в главе рассматривается «смерть от колдовства» (психофизиологическая смерть). Это реальный феномен, когда человек умирает от сильнейшего социального или психологического шока (проклятия). Сапольски объясняет это чрезмерной активацией симпатической системы, приводящей к остановке сердца.",
      "Итог главы",
      "Сердечно-сосудистая система — это «умный» механизм, идеально приспособленный для короткого спринта по саванне. Однако хроническая активация этого механизма из-за чисто психологических причин превращает его в инструмент медленного самоуничтожения, приводя к гипертонии, закупорке сосудов и внезапным катастрофам."
    ],
    "4": [
      "Четвертая глава книги, озаглавленная «Стресс, метаболизм и ликвидация активов», посвящена тому, как наш организм распоряжается своими энергетическими запасами в моменты кризиса и какую цену мы платим за постоянные «набеги на банк».",
      "1. Метаболический банк: как мы копим энергию",
      "Представьте, что ваше тело — это сложная финансовая система. Когда вы плотно поели и отдыхаете на диване, ваш организм занимается накоплением «капитала». Простая «наличка» в виде глюкозы, аминокислот и жирных кислот превращается в сложные «активы»:",
      "* Гликоген (хранится в печени и мышцах);",
      "* Белки (в мышцах);",
      "* Триглицериды (в жировых клетках).",
      "Главным «банкиром», который заведует этими вкладами и планирует ваше метаболическое будущее, является инсулин.",
      "2. Реакция на стресс: срочная ликвидация активов",
      "Когда за вами гонится лев, организму не до долгосрочных инвестиций. Ему нужно немедленно превратить все накопленное имущество в «живые деньги» — энергию для мышц.",
      "1. Остановка вкладов: Симпатическая нервная система выключает «банкира»-инсулина. Глюкокортикоиды блокируют доставку питательных веществ в хранилища.",
      "2. Распродажа имущества: Гормоны стресса (адреналин, норадреналин, глюкагон и глюкокортикоиды) начинают обратный процесс: превращают белки, гликоген и жиры обратно в аминокислоты, глюкозу и жирные кислоты, выбрасывая их в кровь.",
      "3. Глюконеогенез: Печень в экстренном порядке перерабатывает даже аминокислоты в глюкозу — самый доступный источник энергии для спасения шкуры.",
      "3. Почему мы заболеваем: цена хронического стресса",
      "Проблема современного человека в том, что он «ликвидирует активы» не ради побега от льва, а из-за тревожных мыслей.",
      "* Хроническая усталость: Постоянное перемещение энергии из хранилищ в кровь и обратно обходится организму очень дорого. Мы тратим столько сил на эти маневры, что начинаем быстрее уставать.",
      "* Миопатия (атрофия мышц): Если вы месяцами находитесь в стрессе, ваши мышцы постоянно расщепляют белки и не успевают восстанавливаться, что приводит к их истощению.",
      "* Атеросклероз: Тонны жира и глюкозы, постоянно циркулирующие в крови из-за стресса, в итоге оседают на стенках поврежденных сосудов, забивая их.",
      "4. Диабет и метаболический синдром",
      "Глава подробно объясняет связь стресса с нарушениями обмена веществ:",
      "* Диабет 1 типа: Стресс может ускорить проявление симптомов и ухудшить контроль над уровнем сахара.",
      "* Диабет 2 типа: Это болезнь инсулинорезистентности. Постоянные гормоны стресса приказывают клеткам игнорировать инсулин. Если это длится долго, здоровый человек может превратиться в диабетика.",
      "* Метаболический синдром (синдром X): Сапольски описывает это как «целый букет» проблем (давление, ожирение, высокий сахар и холестерин), которые подпитывают друг друга.",
      "Итог главы: Хронический стресс заставляет нас постоянно «снимать деньги со счета» и держать их в крови. В результате наши метаболические банки пустеют (мышцы атрофируются), а кровеносные сосуды забиваются этим невостребованным «мусором». Мы сталкиваемся с аллостатической нагрузкой — износом организма, когда даже при формально нормальных показателях тело уже находится на грани катастрофы."
    ]
  },
  "nl": {
    "2": [
      "Stel je voor dat je rustig in een fauteuil een boek leest. Je lichaam beweegt niet, maar één levendige gedachte — aan een oude krenking, een hartstochtelijke afspraak of een naderende deadline — laat je hart sneller kloppen en je handpalmen vochtig worden. Dat is de magie van hoofdstuk twee: het onthult de verborgen draden tussen onze gedachten en iedere cel van ons lichaam.",
      "Centraal staat het autonome zenuwstelsel, verdeeld in twee eeuwige tegenstanders:",
      "* Het sympathische stelsel is het ‘gaspedaal’. Het schakelt onmiddellijk de vecht-of-vluchtreactie in, laat haren overeind staan en de adrenaline door het bloed razen.",
      "* Het parasympathische stelsel is de ‘rem’. Het zorgt voor rust, slaap, spijsvertering en herstel.",
      "Maar zenuwen zijn slechts snelle boodschappers. De echte macht ligt bij hormonen, en de bronnen vertellen over de ‘grote dirigent’. Wetenschappers beschouwden de hypofyse lange tijd ten onrechte als de ‘meesterklier’. De dramatische wetenschappelijke rivaliteit tussen Roger Guillemin en Andrew Schally liet echter zien dat de hypothalamus de echte heerser is. Jarenlang verwerkten zij tonnen hersenen uit slachthuizen om minuscule hoeveelheden hormonen te vinden waarmee de hersenen het lichaam aansturen.",
      "Wanneer het alarm klinkt, verandert het orkest van ons lichaam van melodie:",
      "1. De ‘soldaten’ komen in actie: de bijnieren geven adrenaline af, die binnen seconden werkt, en glucocorticoïden, die de reactie urenlang onderhouden. De hypofyse geeft prolactine en vasopressine af.",
      "2. De ‘vreedzame bouwprojecten’ stoppen: het lichaam schakelt kostbare langetermijnactiviteiten uit. Insuline daalt — energie wordt verbruikt in plaats van opgeslagen — en voortplantingshormonen (oestrogeen, progesteron en testosteron) en groeihormoon worden onderdrukt.",
      "De bronnen benadrukken dat deze storm niet altijd hetzelfde is. Psychologe Shelley Taylor ontdekte dat stress bij vrouwen vaak niet agressie oproept, maar ‘zorgen en verbinden’, een mechanisme dat sociale banden versterkt.",
      "Conclusie van het hoofdstuk: ons hormoonstelsel is een verfijnd instrument, gemaakt om tijdens een kort gevecht levens te redden. Als we het maandenlang een alarmmars laten spelen zonder de ‘rem’ te laten werken, verandert de symfonie in een requiem voor onze gezondheid."
    ],
    "3": [
      "Hoofdstuk drie, ‘Beroertes, hartaanvallen en voodoodood’, gaat over de invloed van stress op hart en bloedvaten en waarom onze reactie levensgevaarlijk kan worden.",
      "Dit zijn de belangrijkste ideeën:",
      "1. Hoe het hart levens redt (de acute reactie)",
      "Tijdens een lichamelijke crisis, zoals een ontmoeting met een leeuw, reorganiseert het lichaam onmiddellijk de bloedsomloop. De hersenen:",
      "* ‘Geven gas’: schakelen de parasympathische ‘rem’ uit en het sympathische zenuwstelsel in.",
      "* Versnellen het ritme: het hart klopt sneller en krachtiger.",
      "* Verdelen de middelen opnieuw: slagaders naar actieve spieren verwijden, terwijl de bloedtoevoer naar ‘minder belangrijke’ organen, zoals darmen en huid, sterk afneemt.",
      "* Gooien ballast overboord: om het lichaam lichter te maken voor het rennen, probeert het de blaas te legen.",
      "2. Chronische slijtage: wanneer de ‘pomp’ kapotgaat",
      "Het menselijke probleem is dat we dit krachtige mechanisme niet alleen bij een leeuw activeren, maar ook bij psychische zorgen, zoals de rommel in de kamer van een zoon of een deadline.",
      "* Hypertensie: voortdurend hoge bloeddruk verslijt de bloedvaten. Ze worden stijver en dikker om de bloeddruk te weerstaan, waardoor de druk verder stijgt.",
      "* Atherosclerose: waar hoge druk bloedvaten beschadigt, ontstaat ontsteking. Aan deze ‘kuilen’ hechten zich vetten, glucose en ‘slecht’ cholesterol, waardoor atherosclerotische plaques ontstaan.",
      "* C-reactief proteïne (CRP): Sapolsky merkt op dat de CRP-waarde, een ontstekingsmarker, hartziekten veel nauwkeuriger voorspelt dan de cholesterolwaarde.",
      "3. Cardiovasculaire rampen",
      "Chronische stress bereidt de weg voor acute aanvallen:",
      "* Hartinfarct en beroerte: onder de bloeddruk kan een plaque losraken en een nauw vat in het hart (infarct) of de hersenen (beroerte) verstoppen.",
      "* Myocardischemie: bij gezonde mensen verwijden de hartvaten tijdens stress, maar bij iemand met een aandoening kunnen ze juist vernauwen. Daardoor krijgt het hart te weinig zuurstof wanneer het op volle kracht werkt.",
      "* Plotselinge dood: extreme stress kan een fatale ritmestoornis veroorzaken, ventrikelfibrilleren, waarbij het hart chaotisch trilt zonder bloed rond te pompen.",
      "4. Dood door plezier en ‘toverij’",
      "De auteur benadrukt dat het voor het hart niet uitmaakt of de lichamelijke storm voortkomt uit verdriet of uit uitbundige vreugde, zoals een orgasme of een grote prijs: de belasting is hetzelfde. Het hoofdstuk bespreekt ook ‘voodoodood’, of psychofysiologische dood: het verschijnsel waarbij iemand overlijdt na een extreme sociale of psychologische schok, zoals een vervloeking. Sapolsky verklaart dit door overmatige sympathische activatie die tot een hartstilstand leidt.",
      "Conclusie van het hoofdstuk",
      "Het cardiovasculaire stelsel is een ‘slim’ mechanisme, uitstekend aangepast aan een korte sprint over de savanne. Maar chronische activatie om uitsluitend psychologische redenen verandert het in een instrument van langzame zelfvernietiging, met hoge bloeddruk, verstopte vaten en plotselinge rampen als gevolg."
    ],
    "4": [
      "Hoofdstuk vier, ‘Stress, stofwisseling en het liquideren van je bezittingen’, gaat over hoe het lichaam tijdens crises zijn energievoorraden beheert en welke prijs we betalen voor voortdurende ‘overvallen op de bank’.",
      "1. De metabole bank: hoe we energie opslaan",
      "Stel je het lichaam voor als een ingewikkeld financieel systeem. Na een stevige maaltijd, terwijl je op de bank uitrust, verzamelt het ‘kapitaal’. Eenvoudig ‘contant geld’ — glucose, aminozuren en vetzuren — wordt omgezet in complexe ‘bezittingen’:",
      "* Glycogeen (opgeslagen in lever en spieren);",
      "* Eiwitten (in spieren);",
      "* Triglyceriden (in vetcellen).",
      "Insuline is de belangrijkste ‘bankier’ die deze tegoeden beheert en je metabole toekomst plant.",
      "2. De stressreactie: dringende liquidatie van bezittingen",
      "Wanneer een leeuw je achtervolgt, heeft het lichaam geen tijd voor langetermijninvesteringen. Het moet alle opgebouwde bezittingen onmiddellijk omzetten in ‘contant geld’: energie voor de spieren.",
      "1. Stortingen stoppen: het sympathische zenuwstelsel schakelt insuline, de ‘bankier’, uit. Glucocorticoïden blokkeren de toevoer van voedingsstoffen naar de opslag.",
      "2. Bezittingen worden verkocht: stresshormonen — adrenaline, noradrenaline, glucagon en glucocorticoïden — keren het proces om. Ze zetten eiwitten, glycogeen en vetten terug om in aminozuren, glucose en vetzuren en geven die af aan het bloed.",
      "3. Gluconeogenese: de lever zet met spoed zelfs aminozuren om in glucose, de meest direct beschikbare brandstof om je hachje te redden.",
      "3. Waarom we ziek worden: de prijs van chronische stress",
      "Het probleem van de moderne mens is dat hij ‘bezittingen liquideert’ door angstige gedachten, niet om aan een leeuw te ontsnappen.",
      "* Chronische vermoeidheid: voortdurend energie verplaatsen van de opslag naar het bloed en terug is duur. Deze manoeuvres kosten zo veel energie dat we sneller moe worden.",
      "* Myopathie (spieratrofie): bij maandenlange stress breken spieren voortdurend eiwitten af en herstellen ze niet snel genoeg, waardoor ze wegkwijnen.",
      "* Atherosclerose: de tonnen vet en glucose die door stress voortdurend in het bloed circuleren, zetten zich uiteindelijk af op beschadigde vaatwanden en verstoppen die.",
      "4. Diabetes en metabool syndroom",
      "Het hoofdstuk legt het verband tussen stress en stofwisselingsstoornissen uit:",
      "* Diabetes type 1: stress kan klachten sneller zichtbaar maken en de bloedsuikercontrole verslechteren.",
      "* Diabetes type 2: dit is een ziekte van insulineresistentie. Aanhoudende stresshormonen dragen cellen op insuline te negeren. Als dat lang duurt, kan een gezond persoon diabetes ontwikkelen.",
      "* Metabool syndroom (syndroom X): Sapolsky beschrijft een ‘heel boeket’ aan problemen — bloeddruk, obesitas, hoge bloedsuiker en cholesterol — die elkaar versterken.",
      "Conclusie van het hoofdstuk: chronische stress laat ons voortdurend ‘geld opnemen’ en in het bloed houden. Onze metabole banken raken leeg (spieren atrofiëren), terwijl bloedvaten verstopt raken met dit ongebruikte ‘afval’. We krijgen te maken met allostatische belasting: lichamelijke slijtage waarbij het lichaam zelfs bij formeel normale meetwaarden al op de rand van een catastrofe kan staan."
    ]
  }
};

