import type { Language } from "./site-content";

// User-authored study summaries from Google Drive, with translations.
export const moreChapterSummaries: Record<Language, Record<number, string[]>> = {
  "en": {
    "5": [
      "Chapter five, ‘Ulcers, the Runs, and Hot Fudge Sundaes’, explores the complex relationships between stress, appetite, digestion and ulcer disease.",
      "These are the main ideas:",
      "1. Stress and food intake: why we eat (or do not eat)",
      "Stress fundamentally changes eating behaviour, but not equally for everyone: two thirds of people eat more under stress and one third eat less. The summary explains this through competition between two hormones:",
      "* CRH (corticotropin-releasing hormone) appears in the first seconds of stress and suppresses appetite so that eating does not consume energy while escaping a lion.",
      "* Glucocorticoids act more slowly, over minutes and hours, and stimulate appetite, helping replenish energy after a crisis.",
      "* Conclusion: brief, intense stress favours CRH and appetite disappears. Frequent small daily stressors—‘chronic psychological stress’—keep glucocorticoids high, encouraging constant snacking.",
      "2. ‘Apples’ and ‘pears’: where fat goes",
      "Glucocorticoids do more than increase appetite: they tell the body where to store fat. They promote abdominal fat, making a person ‘apple-shaped’.",
      "* Abdominal fat is more hazardous because it more readily reaches the liver, increasing diabetes and heart disease risk.",
      "* An interesting finding: ‘comfort food’, rich in fat and sugar, and abdominal fat accumulation really can reduce the brain's stress response, making people feel better at a cost to health.",
      "3. Stress and the intestines",
      "During acute stress, digestion shuts down because it is energy-intensive, using 10–20% of total energy.",
      "* Why can fear cause diarrhoea? The body tries to shed ‘extra weight’ to run faster. The small intestine becomes inactive while the colon contracts vigorously, expelling contents before water can be absorbed.",
      "* Irritable bowel syndrome (IBS) is a functional disorder highly sensitive to stress. Stress increases the gut's sensitivity to pain, and early childhood trauma can leave it vulnerable for life.",
      "4. The puzzle of stomach ulcers",
      "Ulcers were long attributed solely to stress. After Helicobacter pylori was discovered in the 1980s, medicine swung to the opposite extreme, dismissing stress. Sapolsky describes the truth as lying between these extremes: the bacterium is the ‘loaded gun’, but stress ‘pulls the trigger’.",
      "How stress causes ulcers: the main mechanisms",
      "1. Acid rebound: during stress, the stomach's protective mucus and bicarbonate decrease to save energy. Afterwards, acid production resumes immediately but protection recovers slowly. During this recovery period the stomach begins digesting itself.",
      "2. Reduced blood supply: inadequate blood flow causes tiny infarctions in the stomach wall.",
      "3. Free radicals: when blood returns after stress, harmful substances are released that destroy cells.",
      "4. Immune suppression: chronic stress prevents the body from restraining Helicobacter pylori multiplication.",
      "Chapter conclusion: the gastrointestinal tract is a delicate instrument that responds early to our thoughts. Ulcers arise not because a lion attacked us, but because we repeatedly ‘brake’ and ‘accelerate’ digestion in response to psychological problems."
    ],
    "6": [
      "Chapter six, ‘Dwarfism and the Importance of Mothers’, examines how stress and the emotional environment influence growth from embryonic development through adulthood.",
      "1. Prenatal stress and metabolic programming",
      "Stress experienced during pregnancy leaves a lifelong imprint on the child. This process is called metabolic programming.",
      "* ‘Thrifty’ metabolism: if an embryo receives signals of famine or high stress through maternal glucocorticoids, its body learns to store nutrients as efficiently as possible.",
      "* Consequences: in adulthood, these individuals face increased risks of hypertension, obesity, type 2 diabetes and cardiovascular disease.",
      "* Brain and behaviour: prenatal stress can result in a smaller head at birth, greater anxiety through changes in the amygdala, and poorer memory in old age.",
      "* Across generations: stress effects can reach grandchildren without genetic involvement, through the maternal–foetal circulatory connection.",
      "2. Psychosocial dwarfism",
      "Stress-related dwarfism is a striking example of psychological stress affecting growth.",
      "* The phenomenon: children under severe emotional stress or deprived of love stop growing despite adequate nutrition. They have critically low somatotropin, or growth hormone.",
      "* Mechanisms: besides low growth hormone, excessive sympathetic activity impairs intestinal nutrient absorption.",
      "* Reversibility: removing the stressor—for example, changing the environment or the care staff to whom the child is attached—can allow astonishingly rapid catch-up growth.",
      "3. Maternal care and touch",
      "The sources emphasise that normal development requires ‘love’ in the biological sense: stimulation and touch.",
      "* Harlow's experiments: rhesus monkeys with artificial ‘mothers’ chose the soft mother they could cuddle, rather than the one that provided food.",
      "* Premature babies: Tiffany Field's research found that just 15 minutes of stroking three times daily made premature infants grow 50% faster and develop more actively.",
      "* Deprivation: lack of maternal care in animals produces lifelong elevation of glucocorticoids and slows development of brain regions involved in learning and memory.",
      "4. Growth functions in adults",
      "Adults no longer grow taller, but they continue producing somatotropin.",
      "* Bone repair: adult growth hormone supports continual renewal of bone tissue and ‘patching cracks’ in the body's foundation.",
      "* Stress and osteoporosis: chronic stress and excess glucocorticoids block this renewal and can lead to osteoporosis and skeletal atrophy.",
      "Chapter conclusion: growth depends not only on calories but on psychological wellbeing. Lack of touch and emotional support is a powerful biological stressor that can ‘switch off’ growth and cause irreparable harm for decades."
    ],
    "7": [
      "The seventh chapter, “Sex and the Reproductive System”, explains why, during stress, our body treats reproduction as an unaffordable luxury, switching off sexual desire and reproductive functions to prioritise survival.",
      "Here are the chapter’s main ideas:",
      "1. Male physiology: testosterone and the puzzle of erections",
      "During stress, testosterone production in men drops sharply. The body blocks the process at every level: endorphins switch off signals in the brain, prolactin reduces pituitary sensitivity, and glucocorticoids block the testes’ response. Stress has an even more dramatic effect on the mechanics of sex.",
      "* Parasympathetic and sympathetic activity: A normal erection requires an active parasympathetic nervous system, responsible for rest and relaxation. Ejaculation, by contrast, is triggered by the sympathetic nervous system—the fight-or-flight response.",
      "* Stress disrupts the system: During chronic stress, the sympathetic system is active and the parasympathetic system suppressed, resulting in impotence—the inability to achieve an erection. If an erection is already present and a stressful thought suddenly arises, the system can switch to sympathetic activity too quickly, causing premature ejaculation. Hyenas are an exception in nature: males paradoxically develop erections during stress and social submission, signalling submission to aggressive females.",
      "2. Female physiology: depletion, prolactin and libido",
      "The female reproductive system is equally vulnerable to physical and psychological crises.",
      "* Fat and oestrogen: In women, the adrenal glands produce small amounts of male hormones—androgens—which enzymes in fat cells then convert into oestrogens. If body fat falls critically low because of stress, starvation or exhausting training, as in ballet dancers or runners, androgens accumulate and menstruation becomes irregular or stops altogether.",
      "* Prolactin and contraception: Stress releases prolactin, a hormone that strongly suppresses reproductive function. The same hormone is produced during breastfeeding. Sapolsky cites the San people of the Kalahari: women breastfeed for three years, several times an hour, maintaining high prolactin levels that act as a reliable natural contraceptive.",
      "* Loss of libido: Stress suppresses the production of adrenal androgens and oestrogens, directly reducing sexual desire in women.",
      "3. IVF and pregnancy loss",
      "* Treatment-related stress: In vitro fertilisation (IVF) itself causes enormous stress through painful injections, hormonal swings and anxious waiting. The higher the stress and glucocorticoid levels during an IVF cycle, the lower the probability of success.",
      "* Miscarriage risk: Severe psychological stress can lead to pregnancy loss. During a crisis, the sympathetic nervous system constricts blood vessels and reduces blood flow to the uterus. If this happens frequently, the fetus may suffer from hypoxia—a lack of oxygen.",
      "Chapter conclusion",
      "Stress can disrupt reproduction in many ways. Yet the basic, primitive drive to reproduce is remarkably resilient: studies show that even under the horrific conditions of concentration camps, roughly half of women continued to menstruate. The biological drive to reproduce withstands enormous strain. The finer aspects of sexuality—libido, romantic attraction, pleasure and relaxation—are nevertheless fragile and easily disrupted by everyday psychological stress."
    ],
    "8": [
      "The eighth chapter, “Immunity, Stress, and Disease”, introduces psychoneuroimmunology, the study of the remarkable connections between our thoughts, brain and immune defences.",
      "The chapter challenges popular myths about stress and illness, explaining how we become vulnerable to infections and why “positive thinking” does not cure cancer. These are its main concepts:",
      "1. Immune swings: a surprise for scientists",
      "For a long time, stress was thought simply to suppress immunity to save energy. More recent discoveries, however, revealed a much more complex response:",
      "* Activation phase: During the first 30 minutes of stress, immunity does not decline but increases sharply. Stress hormones, including glucocorticoids and adrenaline, do not deactivate immune cells; they urgently move them from the blood to the frontline, such as the skin, so wounds can heal faster after injury.",
      "* Suppression phase: If stress persists, glucocorticoids begin selectively destroying lymphocytes—immune cells—starting with the oldest and least useful.",
      "* Why suppress immunity? Scientist Allan Munck found that the body deliberately brakes the immune system after its initial mobilisation to prevent an excessive response. If hyperactive immunity is not switched off, it may confuse the body’s own tissues with foreign ones, leading to autoimmune diseases such as multiple sclerosis or rheumatoid arthritis. Failure of this braking system increases autoimmune risk.",
      "2. Pathways to illness",
      "Why do we get ill more often under stress? Sapolsky distinguishes two pathways:",
      "* The psychoneuroimmune pathway: Stress releases hormones that physiologically suppress immunity and increase the likelihood of infection.",
      "* The lifestyle pathway: Under stress or depression, people sleep and eat poorly, forget medication or fail to wear a warm coat in freezing weather. Often it is the stress-related change in lifestyle, rather than the hormones themselves, that causes illness.",
      "3. Colds, herpes and the ingenuity of viruses",
      "* Common colds: Epidemiological evidence and experiments confirm that chronic stress increases the risk of catching a cold.",
      "* Latent viruses: Herpes viruses hide in nerve cells for years, waiting for an opportunity to multiply. How do they detect weakened immunity? Their DNA contains a special sensor that responds to increased blood glucocorticoids. Herpes can also perform a remarkable trick: it stimulates the hypothalamus to produce stress hormones, creating favourable conditions for a flare-up.",
      "4. Cancer and the mythology of miracle cures",
      "Perhaps the most challenging part concerns stress and cancer. In animals, severe stress can accelerate the growth of existing tumours because glucocorticoids promote blood-vessel growth into them—angiogenesis—and supply glucose. In humans, however, there is no reliable evidence that stress causes cancer.",
      "Sapolsky sharply criticises physicians such as Bernie Siegel, author of Love, Medicine and Miracles, who claim that cancer results from insufficient spirituality and can be cured by love and courage alone. This approach is cruel because it blames the victim for incurable illness: if the patient dies, they supposedly did not want to live enough or did not love enough. Cancer is an enormously complex biological problem, not punishment for an incorrect psychological attitude.",
      "5. A historical tragedy: status thymicolymphaticus",
      "The chapter ends with the tragic story of a medical disaster caused by overlooking stress. In the nineteenth century, doctors autopsying infants from poor families—whose chronic stress had shrunk their thymus glands—assumed that a tiny thymus was normal. When a child from a wealthy family died of sudden infant death syndrome, a normal, larger thymus led doctors to diagnose the imaginary disease status thymicolymphaticus. Believing that a healthy thymus compressed the windpipe, they widely prescribed neck irradiation for infants. This caused tens of thousands of thyroid cancers in the twentieth century, stemming from a failure to understand how poverty and stress affect anatomy.",
      "Chapter conclusion: Our immunity is finely tuned to brief stressful crises but vulnerable to chronic anxiety. At the same time, we should avoid extremes and not attribute every human illness exclusively to psychological stress."
    ],
    "9": [
      "The ninth chapter, “Stress and Pain”, begins by asking why pain exists at all. Sapolsky explains that pain is a vital warning of danger. People with pain asymbolia, described here as a congenital inability to feel pain, live in a dangerous world and often sustain severe injuries because their bodies do not signal a threat.",
      "These are the chapter’s main concepts and mechanisms:",
      "1. Pain mechanics: fast and slow fibres",
      "Pain information reaches the spinal cord through two types of nerve fibres:",
      "* Fast fibres react immediately, prompting sudden movements to escape the source of pain, such as pulling a hand away from heat.",
      "* Slow fibres produce lasting, throbbing pain. Their task is to keep us still while a wound heals. Stimulating fast fibres can temporarily switch off slow ones, which explains why we instinctively rub a bruise or scratch an insect bite to relieve throbbing pain. If this mechanism fails, as in diabetes, slow fibres cannot be switched off and even mild discomfort becomes persistent pain.",
      "2. Pain’s subjectivity and the brain",
      "The brain does not passively receive pain signals; it actively interprets them according to context. A severely wounded soldier may request painkillers much less often than a civilian with the same injury in peacetime. Studies also found that patients with a window overlooking trees needed fewer painkillers than those looking at a blank wall.",
      "3. Stress-induced pain relief: analgesia",
      "During acute stress—in battle, while escaping a predator or during sport—the body can temporarily block pain completely. It releases endogenous opioids, including endorphins and enkephalins, which bind to receptors in the brain and spinal cord and interrupt pain signals.",
      "* This mechanism explains the famous runner’s high and much of how acupuncture works.",
      "* The placebo effect also works through the brain’s release of opioids. Giving an opioid-receptor blocker such as naloxone stops the placebo from working.",
      "4. Stress-induced sensitivity to pain",
      "Sometimes stress does the opposite and makes us more vulnerable to pain. The physical signal itself does not increase; our emotional response changes. The amygdala, a centre for fear and anxiety, plays a key role. Anxiety makes the same sensations feel more distressing. Sapolsky discusses fibromyalgia, a puzzling chronic pain syndrome. Doctors long dismissed it as a purely psychosomatic neurosis, but newer findings show heightened activity in emotional brain centres, altered glucocorticoid levels and more of a pain-signalling substance in cerebrospinal fluid.",
      "5. Chronic stress and depletion",
      "Sapolsky highlights a distinctive feature of the pain-relief system. Unlike stress responses such as hormone production, which can fail to stop and eventually harm the body, stress-induced analgesia cannot operate indefinitely. Prolonged stress rapidly depletes endogenous opioid stores. Pain relief is therefore a temporary emergency measure. If stress continues, pain inevitably returns."
    ],
    "10": [
      "Imagine remembering every detail of the day you learned that the Twin Towers had fallen, or the seconds when you narrowly avoided a car crash, yet being unable to remember breakfast two days ago. Chapter ten, “Stress and Memory”, explores this paradox: why stress can dramatically sharpen memory or destroy it.",
      "1. The architecture of memory",
      "Sapolsky begins by explaining that memory is not a single system. A key distinction separates explicit, declarative memory—facts, events and names—from implicit, procedural memory—skills such as cycling or playing tennis. The hippocampus plays a central role in explicit memory.",
      "Memories are not stored in single neurons but distributed across extensive neural networks. Learning occurs when synapses cross a nonlinear excitation threshold, aided by the neurotransmitter glutamate, producing a moment of insight.",
      "2. How stress improves memory: the inverted U",
      "The relationship between stress and memory follows an inverted U. Brief, moderate stress lies on the rising part of the curve, improving memory and concentration.",
      "The sympathetic nervous system releases adrenaline and noradrenaline, while moderate glucocorticoid levels increase glucose delivery to the brain, supplying neurons with more energy. Sensory receptors become more sensitive, and emotionally charged events are burned into memory. Evolutionarily, this is essential: when facing a threat, we need to remember how we got into danger and how to escape.",
      "3. Chronic stress as a destroyer",
      "If stress becomes too intense or lasts for months, the inverted-U curve drops sharply. Memory, especially retrieval of past information, begins to fail. This is particularly apparent in patients with Cushing’s syndrome, which produces excessive stress hormones, or in people taking synthetic glucocorticoids for long periods.",
      "Chronic stress harms the hippocampus on several levels:",
      "* Loss of connectivity: Neuronal extensions—axons and dendrites—shrink and deteriorate, making synaptic networks less complex. Memories do not disappear, but become much harder to access.",
      "* Suppressed neurogenesis: Adult brains were long thought unable to create new cells, but this process was found in the hippocampus. Stress and glucocorticoids strongly inhibit the birth of new neurons.",
      "* Energy deprivation and cell death: After about 30 minutes of continuous stress, glucose delivery to the hippocampus starts to fall, by as much as 25%. Energy-deprived neurons become highly vulnerable: a stroke or minor injury at this point kills more cells. Very prolonged exposure to high stress-hormone levels can kill hippocampal neurons through glucocorticoid neurotoxicity.",
      "4. Physical brain shrinkage in humans",
      "The chapter concludes with troubling findings extending animal research to humans. MRI studies show that conditions associated with severe chronic stress can involve reduced hippocampal volume. Such atrophy is observed in post-traumatic stress disorder (PTSD), prolonged major depression, flight attendants repeatedly crossing time zones with chronic disruption of body rhythms, and normal ageing in older people whose cortisol levels rise over time.",
      "Chapter conclusion: Moderate stress is an ally that helps the brain perform well and record important experiences. But keeping this emergency system active for days and months because of psychological worries can make neural networks shrink and deteriorate, restricting access to our memories."
    ]
  },
  "es": {
    "5": [
      "El quinto capítulo, «Úlceras, la carrera por la sabana y chocolate caliente», aborda las complejas relaciones entre estrés, apetito, digestión y enfermedad ulcerosa.",
      "Estas son las ideas principales:",
      "1. Estrés y alimentación: por qué comemos (o no comemos)",
      "El estrés cambia profundamente la conducta alimentaria, pero de forma desigual: dos tercios de las personas comen más y un tercio menos. El resumen lo explica como una competición entre dos hormonas:",
      "* La CRH (hormona liberadora de corticotropina) aparece en los primeros segundos y suprime el apetito para no gastar energía en comer mientras se huye de un león.",
      "* Los glucocorticoides actúan más lentamente, durante minutos y horas, y estimulan el apetito para reponer energía tras la crisis.",
      "* Conclusión: con estrés breve e intenso predomina la CRH y desaparece el apetito. Los pequeños estresores frecuentes —«estrés psicológico crónico»— mantienen altos los glucocorticoides y fomentan el picoteo constante.",
      "2. «Manzanas» y «peras»: adónde va la grasa",
      "Los glucocorticoides no solo aumentan el apetito: indican dónde almacenar grasa. Favorecen su acumulación abdominal, dando al cuerpo forma de «manzana».",
      "* La grasa abdominal resulta más peligrosa porque llega con mayor facilidad al hígado, aumentando el riesgo de diabetes y cardiopatías.",
      "* Un dato interesante: la «comida reconfortante», grasa y dulce, y la acumulación abdominal pueden reducir la respuesta cerebral al estrés, haciendo sentirse mejor a costa de la salud.",
      "3. Estrés y funcionamiento intestinal",
      "Durante el estrés agudo, la digestión se desconecta porque consume mucha energía: entre el 10 y el 20% del total.",
      "* ¿Por qué el miedo puede causar diarrea? El organismo intenta eliminar «peso extra» para correr más rápido. El intestino delgado se detiene y el grueso se contrae intensamente, expulsando su contenido antes de absorber el agua.",
      "* El síndrome del intestino irritable (SII) es un trastorno funcional muy sensible al estrés. Este aumenta la sensibilidad intestinal al dolor; los traumas infantiles tempranos pueden dejar una vulnerabilidad duradera.",
      "4. El enigma de la úlcera gástrica",
      "Durante mucho tiempo se atribuyeron las úlceras únicamente al estrés. Tras descubrir Helicobacter pylori en los años ochenta, la medicina pasó al extremo contrario y descartó el estrés. Sapolsky sitúa la verdad entre ambos: la bacteria es la «pistola cargada» y el estrés «aprieta el gatillo».",
      "Cómo provoca úlceras el estrés: mecanismos principales",
      "1. Rebote ácido: durante el estrés disminuyen el moco y el bicarbonato protectores para ahorrar energía. Después, la producción de ácido vuelve inmediatamente, pero la protección se recupera lentamente. En ese intervalo, el estómago empieza a digerirse a sí mismo.",
      "2. Menor riego sanguíneo: la falta de sangre causa pequeños infartos en la pared gástrica.",
      "3. Radicales libres: al regresar la sangre tras el estrés se liberan sustancias dañinas que destruyen células.",
      "4. Supresión inmunitaria: el estrés crónico dificulta contener la multiplicación de Helicobacter pylori.",
      "Conclusión del capítulo: el aparato digestivo es un instrumento delicado que responde pronto a nuestros pensamientos. La úlcera no aparece porque nos ataque un león, sino por «frenar» y «acelerar» repetidamente la digestión ante problemas psicológicos."
    ],
    "6": [
      "El sexto capítulo, «Enanismo y la importancia de las madres», examina cómo el estrés y el entorno emocional influyen en el crecimiento desde el período embrionario hasta la vida adulta.",
      "1. Estrés prenatal y programación metabólica",
      "El estrés materno durante el embarazo deja una huella en toda la vida del niño. Este proceso se denomina programación metabólica.",
      "* Metabolismo «ahorrador»: si el embrión recibe señales de hambre o estrés intenso mediante glucocorticoides maternos, aprende a almacenar nutrientes con máxima eficiencia.",
      "* Consecuencias: en la edad adulta aumenta el riesgo de hipertensión, obesidad, diabetes tipo 2 y enfermedades cardiovasculares.",
      "* Cerebro y conducta: el estrés prenatal puede asociarse con menor tamaño de la cabeza al nacer, más ansiedad por cambios en la amígdala y peor memoria en la vejez.",
      "* Transmisión generacional: sus efectos pueden llegar a los nietos sin intervención genética, mediante la conexión circulatoria maternofetal.",
      "2. Enanismo psicosocial",
      "El enanismo relacionado con el estrés ilustra de forma llamativa su influencia psicológica sobre el crecimiento.",
      "* El fenómeno: niños sometidos a estrés emocional grave o privados de afecto dejan de crecer pese a una alimentación suficiente. Presentan niveles críticamente bajos de somatotropina, la hormona del crecimiento.",
      "* Mecanismos: además del déficit hormonal, la actividad simpática excesiva dificulta la absorción intestinal de nutrientes.",
      "* Reversibilidad: eliminar el estresor —por ejemplo, cambiar el entorno o el personal sanitario al que el niño está vinculado— puede permitir recuperar el crecimiento a una velocidad extraordinaria.",
      "3. Cuidado materno y contacto",
      "Las fuentes subrayan que el desarrollo normal requiere «amor» en sentido biológico: estimulación y contacto físico.",
      "* Experimentos de Harlow: los macacos rhesus con «madres» artificiales elegían a la madre suave a la que podían abrazarse, no a la que ofrecía alimento.",
      "* Bebés prematuros: los estudios de Tiffany Field mostraron que 15 minutos de caricias tres veces al día hacían crecer a los prematuros un 50% más rápido y favorecían su desarrollo.",
      "* Privación: la falta de cuidado materno en animales eleva los glucocorticoides de por vida y ralentiza el desarrollo de regiones cerebrales relacionadas con aprendizaje y memoria.",
      "4. La función del crecimiento en adultos",
      "Los adultos ya no aumentan de estatura, pero siguen produciendo somatotropina.",
      "* Reparación ósea: la hormona del crecimiento mantiene la renovación del hueso y «repara grietas» en los cimientos del organismo.",
      "* Estrés y osteoporosis: el estrés crónico y el exceso de glucocorticoides bloquean esta renovación y pueden provocar osteoporosis y atrofia esquelética.",
      "Conclusión del capítulo: crecer no depende solo de las calorías, sino del bienestar psicológico. La falta de contacto y apoyo emocional es un potente estresor biológico capaz de «apagar» el crecimiento y causar daños irreparables durante décadas."
    ],
    "7": [
      "El séptimo capítulo, «Sexo y sistema reproductor», explica por qué, durante el estrés, el organismo considera la reproducción un lujo inasequible y desactiva el deseo sexual y las funciones reproductivas para dar prioridad a la supervivencia.",
      "Estas son las ideas principales del capítulo:",
      "1. Fisiología masculina: testosterona y el enigma de la erección",
      "Durante el estrés, la producción de testosterona en los hombres cae bruscamente. El organismo bloquea el proceso en todos sus niveles: las endorfinas apagan señales cerebrales, la prolactina reduce la sensibilidad de la hipófisis y los glucocorticoides bloquean la respuesta de los testículos. El efecto del estrés sobre la mecánica sexual es aún más notable.",
      "* Parasimpático y simpático: Una erección normal requiere la actividad del sistema nervioso parasimpático, responsable del reposo y la relajación. La eyaculación, en cambio, la desencadena el sistema simpático, asociado a la respuesta de lucha o huida.",
      "* El estrés altera el sistema: En el estrés crónico, el simpático está activo y el parasimpático inhibido, lo que produce impotencia, es decir, incapacidad para lograr una erección. Si ya hay una erección y aparece un pensamiento estresante, el sistema puede pasar demasiado rápido a la actividad simpática y provocar eyaculación precoz. Las hienas constituyen una excepción: los machos presentan erecciones precisamente en situaciones de estrés y subordinación social, como señal de sumisión ante hembras agresivas.",
      "2. Fisiología femenina: agotamiento, prolactina y libido",
      "El sistema reproductor femenino es igualmente vulnerable a las crisis físicas y psicológicas.",
      "* Grasa y estrógenos: En las mujeres, las suprarrenales producen pequeñas cantidades de hormonas masculinas, los andrógenos, que después se transforman en estrógenos mediante enzimas de las células grasas. Si la grasa corporal desciende a niveles críticos por estrés, hambre o entrenamiento extenuante, como en bailarinas o corredoras, se acumulan andrógenos y el ciclo menstrual se altera o desaparece.",
      "* Prolactina y anticoncepción: El estrés libera prolactina, que inhibe intensamente la función reproductiva. Esta hormona también se produce durante la lactancia. Sapolsky cita a los san del Kalahari: las mujeres amamantan durante tres años varias veces por hora, manteniendo niveles altos de prolactina que funcionan como anticonceptivo natural fiable.",
      "* Pérdida de libido: El estrés inhibe la producción de andrógenos suprarrenales y estrógenos, reduciendo directamente el deseo sexual femenino.",
      "3. FIV y pérdida del embarazo",
      "* Estrés del tratamiento: La fecundación in vitro (FIV) genera un enorme estrés por las inyecciones dolorosas, las oscilaciones hormonales y la espera angustiosa. Cuanto mayores son el estrés y los glucocorticoides durante el ciclo, menor es la probabilidad de éxito.",
      "* Riesgo de aborto espontáneo: Un estrés psicológico intenso puede provocar la pérdida del embarazo. Durante una crisis, el sistema simpático contrae los vasos sanguíneos y reduce el flujo hacia el útero. Si ocurre con frecuencia, el feto puede sufrir hipoxia, es decir, falta de oxígeno.",
      "Conclusión del capítulo",
      "El estrés puede alterar la reproducción de muchas formas. Sin embargo, el impulso básico y primitivo de reproducirse es extraordinariamente resistente: los estudios muestran que incluso en las terribles condiciones de los campos de concentración, aproximadamente la mitad de las mujeres seguían menstruando. El reflejo biológico de perpetuar la especie soporta cargas enormes. Los aspectos más delicados de la sexualidad —libido, atracción romántica, placer y relajación— son mucho más frágiles y se alteran fácilmente por el estrés psicológico cotidiano."
    ],
    "8": [
      "El octavo capítulo, «Inmunidad, estrés y enfermedad», nos introduce en la psiconeuroinmunología, que estudia las sorprendentes conexiones entre nuestros pensamientos, el cerebro y las defensas inmunitarias.",
      "El capítulo cuestiona mitos populares sobre estrés y enfermedad, explica cómo nos hacemos vulnerables a las infecciones y por qué el «pensamiento positivo» no cura el cáncer. Estas son sus ideas principales:",
      "1. Oscilaciones inmunitarias: una sorpresa para la ciencia",
      "Durante mucho tiempo se pensó que el estrés simplemente inhibía la inmunidad para ahorrar energía. Sin embargo, descubrimientos posteriores mostraron una respuesta mucho más compleja:",
      "* Fase de activación: Durante los primeros 30 minutos de estrés, la inmunidad no disminuye, sino que aumenta intensamente. Las hormonas del estrés, incluidos los glucocorticoides y la adrenalina, no desactivan las células inmunitarias: las envían urgentemente desde la sangre al frente, por ejemplo a la piel, para acelerar la cicatrización en caso de lesión.",
      "* Fase de inhibición: Si el estrés se prolonga, los glucocorticoides empiezan a destruir selectivamente linfocitos, comenzando por los más viejos y menos útiles.",
      "* ¿Por qué inhibirla? Allan Munck descubrió que el organismo frena deliberadamente al sistema inmunitario tras la movilización inicial para evitar una reacción excesiva. Si no se desactiva una inmunidad hiperactiva, puede confundir tejidos propios con extraños y provocar enfermedades autoinmunes, como esclerosis múltiple o artritis reumatoide. Cuando falla este freno, aumenta el riesgo autoinmune.",
      "2. Vías hacia la enfermedad",
      "¿Por qué enfermamos más durante el estrés? Sapolsky distingue dos vías:",
      "* Vía psiconeuroinmunitaria: El estrés libera hormonas que inhiben fisiológicamente la inmunidad y aumentan la probabilidad de infección.",
      "* Vía del estilo de vida: Bajo estrés o depresión, dormimos y comemos peor, olvidamos la medicación o no nos abrigamos cuando hace mucho frío. A menudo, la causa de la enfermedad es el cambio de hábitos provocado por el estrés y no las hormonas por sí mismas.",
      "3. Resfriados, herpes y la astucia de los virus",
      "* Resfriados: Los datos epidemiológicos y experimentales confirman que el estrés crónico aumenta el riesgo de resfriarse.",
      "* Virus latentes: Los virus del herpes se esconden durante años en las neuronas, esperando una oportunidad para multiplicarse. ¿Cómo detectan que la inmunidad ha bajado? Su ADN contiene un sensor que responde al aumento de glucocorticoides en sangre. Además, el herpes puede estimular al hipotálamo para que produzca hormonas del estrés y crear así condiciones favorables para una reactivación.",
      "4. Cáncer y mitología de las curaciones milagrosas",
      "La parte quizá más polémica trata del estrés y el cáncer. En animales, el estrés intenso puede acelerar el crecimiento de tumores existentes porque los glucocorticoides favorecen la formación de vasos sanguíneos en el tumor, la angiogénesis, y le aportan glucosa. En humanos, sin embargo, no hay pruebas fiables de que el estrés cause cáncer.",
      "Sapolsky critica con firmeza a médicos como Bernie Siegel, autor de Amor, medicina y milagros, que atribuyen el cáncer a una espiritualidad insuficiente y afirman que basta el amor y el valor para curarlo. Este enfoque es cruel porque culpa a la víctima de una enfermedad incurable: si muere, supuestamente no quiso vivir lo suficiente o no amó bastante. El cáncer es un problema biológico enormemente complejo, no un castigo por una actitud psicológica incorrecta.",
      "5. Una tragedia histórica: status thymicolymphaticus",
      "El capítulo termina con una catástrofe médica causada por ignorar el estrés. En el siglo XIX, los médicos que realizaban autopsias a bebés de familias pobres, cuyo estrés crónico había reducido el timo, creyeron que un timo diminuto era normal. Cuando un niño de una familia rica moría por muerte súbita infantil, su timo sano y de mayor tamaño llevaba al diagnóstico de una enfermedad imaginaria: status thymicolymphaticus. Al creer que el timo sano comprimía la tráquea, se prescribió masivamente irradiación del cuello a bebés. Esto causó decenas de miles de cánceres de tiroides en el siglo XX por no comprender cómo afectan el estrés y la pobreza a la anatomía.",
      "Conclusión del capítulo: La inmunidad está ajustada a crisis breves, pero es vulnerable a la ansiedad crónica. Aun así, hay que evitar extremos y no atribuir todas las enfermedades humanas exclusivamente al estrés psicológico."
    ],
    "9": [
      "El noveno capítulo, «Estrés y dolor», comienza preguntándose para qué sirve el dolor. Sapolsky explica que es una señal vital de peligro. Las personas con asimbolia del dolor, descrita aquí como una incapacidad congénita para sentirlo, viven en un mundo peligroso y sufren lesiones graves porque su cuerpo no les avisa de las amenazas.",
      "Estos son los principales conceptos y mecanismos del capítulo:",
      "1. Mecánica del dolor: fibras rápidas y lentas",
      "La información dolorosa llega a la médula espinal por dos tipos de fibras nerviosas:",
      "* Las fibras rápidas reaccionan inmediatamente y provocan movimientos bruscos para escapar de la fuente del dolor, como retirar la mano de algo caliente.",
      "* Las fibras lentas producen dolor prolongado y pulsátil. Su función es mantenernos inmóviles mientras cicatriza la herida. Estimular las fibras rápidas puede desactivar temporalmente las lentas; por eso frotamos instintivamente un golpe o rascamos una picadura para aliviar el dolor pulsátil. Si el mecanismo falla, como en la diabetes, las fibras lentas no se desactivan y una molestia leve puede convertirse en dolor persistente.",
      "2. Subjetividad del dolor y papel del cerebro",
      "El cerebro no recibe pasivamente señales dolorosas: las interpreta según el contexto. Un soldado gravemente herido puede pedir analgésicos con menos frecuencia que un civil con la misma lesión en tiempos de paz. Los estudios también encontraron que los pacientes con vistas a árboles necesitaban menos analgésicos que quienes miraban una pared.",
      "3. Alivio del dolor inducido por estrés: analgesia",
      "Durante el estrés agudo —en una batalla, al huir de un depredador o al competir— el organismo puede bloquear temporalmente el dolor. Libera opioides endógenos, como endorfinas y encefalinas, que se unen a receptores cerebrales y medulares e interrumpen las señales dolorosas.",
      "* Este mecanismo explica la conocida euforia del corredor y buena parte del funcionamiento de la acupuntura.",
      "* El efecto placebo también actúa mediante la liberación cerebral de opioides. Al administrar un bloqueador de sus receptores, como la naloxona, el placebo deja de actuar.",
      "4. Hipersensibilidad al dolor por estrés",
      "A veces el estrés hace lo contrario y aumenta la vulnerabilidad al dolor. No aumenta la señal física, sino que cambia la respuesta emocional. La amígdala, relacionada con miedo y ansiedad, desempeña un papel fundamental: la ansiedad hace que las mismas sensaciones resulten más angustiosas. Sapolsky menciona la fibromialgia, un enigmático síndrome de dolor crónico. Durante mucho tiempo se consideró una neurosis puramente psicosomática, pero datos posteriores muestran mayor actividad en centros emocionales cerebrales, niveles alterados de glucocorticoides y más cantidad de una sustancia transmisora del dolor en el líquido cefalorraquídeo.",
      "5. Estrés crónico y agotamiento",
      "Sapolsky destaca una peculiaridad del sistema analgésico. A diferencia de respuestas como la producción hormonal, que pueden no apagarse a tiempo y acabar dañando el organismo, la analgesia por estrés no puede funcionar indefinidamente. El estrés prolongado agota rápidamente las reservas de opioides endógenos. Por eso, el alivio es una medida temporal de emergencia. Si el estrés continúa, el dolor regresa inevitablemente."
    ],
    "10": [
      "Imagina recordar cada detalle del día en que supiste de la caída de las Torres Gemelas, o los segundos en que evitaste por poco un accidente, pero no qué desayunaste hace dos días. El décimo capítulo, «Estrés y memoria», explora esa paradoja: por qué el estrés puede agudizar extraordinariamente la memoria o destruirla.",
      "1. Arquitectura de la memoria",
      "Sapolsky explica primero que la memoria no es un sistema único. La distinción principal separa la memoria explícita o declarativa —hechos, acontecimientos y nombres— de la implícita o procedimental —habilidades como montar en bicicleta o jugar al tenis—. El hipocampo desempeña un papel central en la memoria explícita.",
      "Los recuerdos no se guardan en neuronas individuales, sino que se distribuyen por amplias redes neuronales. El aprendizaje ocurre cuando las sinapsis superan un umbral no lineal de excitación, gracias al neurotransmisor glutamato, y aparece un momento de comprensión.",
      "2. Cómo mejora el estrés la memoria: la U invertida",
      "La relación entre estrés y memoria sigue una U invertida. El estrés breve y moderado está en la parte ascendente: mejora memoria y concentración.",
      "El sistema simpático libera adrenalina y noradrenalina, mientras que niveles moderados de glucocorticoides aumentan el aporte de glucosa al cerebro y dan más energía a las neuronas. Los receptores sensoriales se vuelven más sensibles y los acontecimientos emotivos quedan grabados intensamente. Evolutivamente es esencial: ante una amenaza, necesitamos recordar cómo llegamos al peligro y cómo escapar.",
      "3. El estrés crónico como destructor",
      "Si el estrés es demasiado intenso o dura meses, la curva cae rápidamente. La memoria, especialmente la recuperación de información pasada, empieza a fallar. Se observa con claridad en pacientes con síndrome de Cushing, que produce un exceso de hormonas del estrés, o en quienes toman glucocorticoides sintéticos durante mucho tiempo.",
      "El estrés crónico perjudica al hipocampo en varios niveles:",
      "* Pérdida de conectividad: Las prolongaciones neuronales, axones y dendritas, se encogen y deterioran, reduciendo la complejidad de las redes sinápticas. Los recuerdos no desaparecen, pero acceder a ellos resulta mucho más difícil.",
      "* Inhibición de la neurogénesis: Durante mucho tiempo se creyó que el cerebro adulto no creaba células nuevas, pero se descubrió este proceso en el hipocampo. El estrés y los glucocorticoides inhiben intensamente el nacimiento de nuevas neuronas.",
      "* Falta de energía y muerte celular: Tras unos 30 minutos de estrés continuo, el aporte de glucosa al hipocampo empieza a bajar, hasta un 25%. Las neuronas sin suficiente energía se vuelven muy vulnerables: un ictus o una lesión pequeña en ese momento mata más células. Una exposición muy prolongada a niveles altos de hormonas del estrés puede matar neuronas hipocampales mediante la neurotoxicidad de los glucocorticoides.",
      "4. Reducción física del cerebro en humanos",
      "El capítulo termina con hallazgos preocupantes que extienden a humanos la investigación animal. Las resonancias muestran que las condiciones asociadas a estrés crónico intenso pueden acompañarse de menor volumen hipocampal. Se observa esta atrofia en el trastorno por estrés postraumático, la depresión mayor prolongada, auxiliares de vuelo que cruzan repetidamente husos horarios con alteración crónica de ritmos biológicos y personas mayores cuyo cortisol aumenta con los años.",
      "Conclusión del capítulo: El estrés moderado es un aliado que ayuda al cerebro a rendir y registrar experiencias importantes. Pero mantener activo este sistema de emergencia durante días y meses por preocupaciones psicológicas puede deteriorar y reducir las redes neuronales, dificultando el acceso a nuestros recuerdos."
    ]
  },
  "nl": {
    "5": [
      "Hoofdstuk vijf, ‘Maagzweren, de race op de savanne en warme chocolademelk’, gaat over de ingewikkelde relaties tussen stress, eetlust, spijsvertering en maagzweren.",
      "Dit zijn de belangrijkste ideeën:",
      "1. Stress en eten: waarom we wel of niet eten",
      "Stress verandert eetgedrag ingrijpend, maar niet bij iedereen hetzelfde: twee derde eet meer en een derde minder. Het overzicht verklaart dit met de strijd tussen twee hormonen:",
      "* CRH (corticotropinevrijmakend hormoon) verschijnt in de eerste seconden en onderdrukt de eetlust, zodat eten geen energie kost tijdens een vlucht voor een leeuw.",
      "* Glucocorticoïden werken langzamer, over minuten en uren, en stimuleren de eetlust om na de crisis energie aan te vullen.",
      "* Conclusie: bij korte, hevige stress wint CRH en verdwijnt de eetlust. Kleine, herhaalde dagelijkse stressoren —‘chronische psychologische stress’— houden glucocorticoïden hoog en lokken voortdurend snacken uit.",
      "2. ‘Appels’ en ‘peren’: waar het vet naartoe gaat",
      "Glucocorticoïden verhogen niet alleen de eetlust: ze bepalen ook waar vet wordt opgeslagen. Ze bevorderen buikvet, waardoor iemand een ‘appelvorm’ krijgt.",
      "* Buikvet is gevaarlijker omdat het gemakkelijker de lever bereikt en het risico op diabetes en hartziekten verhoogt.",
      "* Een interessant gegeven: vet en zoet ‘troosteten’ en buikvet kunnen de stressreactie van de hersenen verminderen. Mensen voelen zich beter, maar betalen met hun gezondheid.",
      "3. Stress en de darmen",
      "Bij acute stress wordt de spijsvertering uitgeschakeld omdat deze veel energie vraagt: 10–20% van het totaal.",
      "* Waarom kan angst diarree veroorzaken? Het lichaam probeert ‘extra gewicht’ kwijt te raken om sneller te rennen. De dunne darm valt stil, terwijl de dikke darm krachtig samentrekt en de inhoud loost voordat het water is opgenomen.",
      "* Het prikkelbaredarmsyndroom (PDS) is een functionele stoornis die sterk op stress reageert. Stress maakt de darmen gevoeliger voor pijn; vroege jeugdtrauma's kunnen een levenslange kwetsbaarheid achterlaten.",
      "4. Het raadsel van de maagzweer",
      "Maagzweren werden lang uitsluitend aan stress toegeschreven. Na de ontdekking van Helicobacter pylori in de jaren tachtig sloeg de geneeskunde door naar het andere uiterste en verwierp stress. Volgens Sapolsky ligt de waarheid ertussen: de bacterie is het ‘geladen pistool’, maar stress ‘haalt de trekker over’.",
      "Hoe stress maagzweren veroorzaakt: de belangrijkste mechanismen",
      "1. Zuurrebound: tijdens stress nemen beschermend slijm en bicarbonaat af om energie te sparen. Daarna hervat de zuurproductie onmiddellijk, maar de bescherming herstelt langzaam. In die herstelperiode begint de maag zichzelf te verteren.",
      "2. Minder doorbloeding: een bloedtekort veroorzaakt kleine infarcten in de maagwand.",
      "3. Vrije radicalen: wanneer het bloed terugkeert, komen schadelijke stoffen vrij die cellen vernietigen.",
      "4. Immuunonderdrukking: chronische stress bemoeilijkt het afremmen van de vermenigvuldiging van Helicobacter pylori.",
      "Conclusie van het hoofdstuk: het maag-darmkanaal is een fijn instrument dat vroeg op gedachten reageert. Een maagzweer ontstaat niet doordat een leeuw ons aanvalt, maar doordat we de spijsvertering steeds ‘afremmen’ en ‘gas geven’ bij psychologische problemen."
    ],
    "6": [
      "Hoofdstuk zes, ‘Dwerggroei en het belang van moeders’, onderzoekt hoe stress en de emotionele omgeving groei beïnvloeden, vanaf het embryonale stadium tot de volwassenheid.",
      "1. Prenatale stress en metabole programmering",
      "Stress tijdens de zwangerschap drukt een levenslang stempel op het kind. Dit heet metabole programmering.",
      "* Een ‘zuinige’ stofwisseling: ontvangt een embryo via moederlijke glucocorticoïden signalen van honger of hevige stress, dan leert het voedingsstoffen zo efficiënt mogelijk op te slaan.",
      "* Gevolgen: later is het risico op hypertensie, obesitas, diabetes type 2 en hart- en vaatziekten verhoogd.",
      "* Hersenen en gedrag: prenatale stress kan leiden tot een kleiner hoofd bij de geboorte, meer angst door veranderingen in de amygdala en een slechter geheugen op latere leeftijd.",
      "* Over generaties heen: stresseffecten kunnen zonder genetische overdracht de kleinkinderen bereiken via de moederlijke–foetale bloedsomloopverbinding.",
      "2. Psychosociale dwerggroei",
      "Stressgerelateerde dwerggroei is een opvallend voorbeeld van psychologische invloed op groei.",
      "* Het verschijnsel: kinderen onder ernstige emotionele stress of zonder liefde stoppen met groeien ondanks voldoende voeding. Zij hebben een kritiek laag niveau van somatotropine, of groeihormoon.",
      "* Mechanismen: naast weinig groeihormoon belemmert overmatige sympathische activiteit de opname van voedingsstoffen in de darmen.",
      "* Omkeerbaarheid: het wegnemen van de stressor —bijvoorbeeld door een andere omgeving of ander zorgpersoneel waaraan het kind gehecht is— kan verbazingwekkend snelle inhaalgroei mogelijk maken.",
      "3. Moederlijke zorg en aanraking",
      "De bronnen benadrukken dat normale ontwikkeling ‘liefde’ in biologische zin vereist: stimulatie en aanraking.",
      "* Harlows experimenten: rhesusaapjes met kunstmatige ‘moeders’ kozen de zachte moeder om tegenaan te kruipen, niet de moeder die voedsel gaf.",
      "* Premature baby's: onderzoek van Tiffany Field liet zien dat 15 minuten strelen, driemaal per dag, premature baby's 50% sneller deed groeien en hun ontwikkeling stimuleerde.",
      "* Deprivatie: gebrek aan moederlijke zorg veroorzaakt bij dieren levenslang hogere glucocorticoïden en tragere ontwikkeling van hersengebieden voor leren en geheugen.",
      "4. De groeifunctie bij volwassenen",
      "Volwassenen worden niet langer, maar blijven somatotropine produceren.",
      "* Botherstel: groeihormoon ondersteunt de voortdurende vernieuwing van botweefsel en ‘dicht scheuren’ in de fundering van het lichaam.",
      "* Stress en osteoporose: chronische stress en te veel glucocorticoïden blokkeren dit herstel, wat osteoporose en skeletatrofie kan veroorzaken.",
      "Conclusie van het hoofdstuk: groei draait niet alleen om calorieën, maar ook om psychisch welzijn. Gebrek aan aanraking en emotionele steun is een krachtige biologische stressor die groei kan ‘uitschakelen’ en tientallen jaren onherstelbare schade kan aanrichten."
    ],
    "7": [
      "Het zevende hoofdstuk, ‘Seks en het voortplantingsstelsel’, legt uit waarom ons lichaam voortplanting tijdens stress als een onbetaalbare luxe beschouwt en seksueel verlangen en voortplantingsfuncties uitschakelt om te overleven.",
      "Dit zijn de belangrijkste ideeën uit het hoofdstuk:",
      "1. Mannelijke fysiologie: testosteron en het raadsel van de erectie",
      "Tijdens stress daalt de testosteronproductie bij mannen sterk. Het lichaam blokkeert dit proces op alle niveaus: endorfinen schakelen signalen in de hersenen uit, prolactine vermindert de gevoeligheid van de hypofyse en glucocorticoïden blokkeren de reactie van de teelballen. De invloed van stress op de mechaniek van seks is nog ingrijpender.",
      "* Parasympathisch en sympathisch: Voor een normale erectie is een actief parasympathisch zenuwstelsel nodig, dat rust en ontspanning ondersteunt. Ejaculatie wordt juist door het sympathische zenuwstelsel gestart: de vecht-of-vluchtreactie.",
      "* Stress verstoort het systeem: Bij chronische stress is het sympathische stelsel actief en het parasympathische onderdrukt, waardoor impotentie ontstaat: geen erectie kunnen krijgen. Als er al een erectie is en plotseling een stressvolle gedachte opkomt, kan het systeem te snel overschakelen naar sympathische activiteit en een voortijdige zaadlozing veroorzaken. Hyena’s vormen een uitzondering: mannetjes krijgen juist bij stress en sociale onderwerping een erectie, als teken van onderdanigheid tegenover agressieve vrouwtjes.",
      "2. Vrouwelijke fysiologie: uitputting, prolactine en libido",
      "Het vrouwelijke voortplantingsstelsel is even kwetsbaar voor lichamelijke en psychologische crises.",
      "* Vet en oestrogeen: Bij vrouwen maken de bijnieren kleine hoeveelheden mannelijke hormonen, androgenen, aan. Enzymen in vetcellen zetten die vervolgens om in oestrogenen. Als de hoeveelheid lichaamsvet door stress, verhongering of uitputtende training, bijvoorbeeld bij ballerina’s of hardloopsters, kritiek laag wordt, hopen androgenen zich op en raakt de menstruatiecyclus verstoord of stopt deze helemaal.",
      "* Prolactine en anticonceptie: Stress maakt prolactine vrij, dat de voortplantingsfunctie sterk onderdrukt. Dit hormoon wordt ook tijdens borstvoeding geproduceerd. Sapolsky noemt de San in de Kalahari: vrouwen geven drie jaar lang meerdere keren per uur borstvoeding, waardoor het prolactinegehalte hoog blijft en als betrouwbare natuurlijke anticonceptie werkt.",
      "* Verlies van libido: Stress onderdrukt de productie van bijnierandrogenen en oestrogenen en vermindert daardoor rechtstreeks het seksuele verlangen bij vrouwen.",
      "3. IVF en zwangerschapsverlies",
      "* Stress door behandeling: In-vitrofertilisatie (IVF) veroorzaakt op zichzelf veel stress door pijnlijke injecties, hormoonschommelingen en gespannen wachten. Hoe hoger de stress en het glucocorticoïdengehalte tijdens een IVF-cyclus, hoe kleiner de kans op succes.",
      "* Risico op een miskraam: Ernstige psychologische stress kan tot zwangerschapsverlies leiden. Tijdens een crisis vernauwt het sympathische zenuwstelsel bloedvaten, waardoor minder bloed naar de baarmoeder stroomt. Als dit vaak gebeurt, kan de foetus last krijgen van hypoxie: zuurstoftekort.",
      "Conclusie van het hoofdstuk",
      "Stress kan de voortplanting op veel manieren verstoren. Toch is de elementaire, primitieve voortplantingsdrang opmerkelijk veerkrachtig: onderzoek laat zien dat zelfs onder de gruwelijke omstandigheden in concentratiekampen ongeveer de helft van de vrouwen bleef menstrueren. De biologische voortplantingsreflex doorstaat enorme belasting. De fijnere kanten van seksualiteit —libido, romantische aantrekkingskracht, plezier en ontspanning— zijn echter kwetsbaar en raken gemakkelijk verstoord door dagelijkse psychologische stress."
    ],
    "8": [
      "Het achtste hoofdstuk, ‘Immuniteit, stress en ziekte’, introduceert de psychoneuroimmunologie: het onderzoek naar de opmerkelijke verbanden tussen gedachten, hersenen en afweer.",
      "Het hoofdstuk ontkracht populaire mythen over stress en ziekte. Het legt uit hoe we vatbaar worden voor infecties en waarom ‘positief denken’ kanker niet geneest. Dit zijn de kernideeën:",
      "1. Schommelende afweer: een verrassing voor wetenschappers",
      "Lange tijd dacht men dat stress de afweer simpelweg onderdrukt om energie te besparen. Latere ontdekkingen lieten echter een veel complexere reactie zien:",
      "* Activeringsfase: In de eerste 30 minuten van stress neemt de afweer niet af, maar juist sterk toe. Stresshormonen, waaronder glucocorticoïden en adrenaline, schakelen afweercellen niet uit. Ze sturen ze met spoed vanuit het bloed naar de frontlinie, bijvoorbeeld de huid, zodat wonden na letsel sneller kunnen genezen.",
      "* Onderdrukkingsfase: Als stress aanhoudt, beginnen glucocorticoïden gericht lymfocyten, afweercellen, te vernietigen, te beginnen met de oudste en minst bruikbare.",
      "* Waarom onderdrukken? Wetenschapper Allan Munck ontdekte dat het lichaam de afweer na de eerste mobilisatie bewust afremt om overreactie te voorkomen. Als een overactieve afweer niet wordt uitgeschakeld, kan deze eigen weefsel voor lichaamsvreemd aanzien en auto-immuunziekten zoals multiple sclerose of reumatoïde artritis veroorzaken. Een storing in dit remsysteem verhoogt dat risico.",
      "2. Routes naar ziekte",
      "Waarom worden we onder stress vaker ziek? Sapolsky onderscheidt twee routes:",
      "* De psychoneuro-immunologische route: Stress maakt hormonen vrij die de afweer fysiologisch onderdrukken en de kans op infecties vergroten.",
      "* De leefstijlroute: Bij stress of depressie slapen en eten mensen slechter, vergeten ze medicijnen of trekken ze bij vorst geen warme jas aan. Vaak is de veranderde leefstijl door stress, en niet het hormoon zelf, de werkelijke oorzaak van ziekte.",
      "3. Verkoudheid, herpes en slimme virussen",
      "* Verkoudheid: Epidemiologisch onderzoek en experimenten bevestigen dat chronische stress de kans op verkoudheid vergroot.",
      "* Latente virussen: Herpesvirussen verbergen zich jarenlang in zenuwcellen en wachten op een kans om zich te vermenigvuldigen. Hoe merken ze dat de afweer verzwakt is? Hun DNA bevat een sensor die reageert op meer glucocorticoïden in het bloed. Herpes kan bovendien de hypothalamus zelf stimuleren om stresshormonen te produceren en zo gunstige omstandigheden voor een opvlamming creëren.",
      "4. Kanker en de mythe van wonderbaarlijke genezing",
      "Het scherpste deel gaat wellicht over stress en kanker. Bij dieren kan ernstige stress bestaande tumoren sneller laten groeien, doordat glucocorticoïden de ingroei van bloedvaten, angiogenese, bevorderen en glucose leveren. Bij mensen bestaat echter geen betrouwbaar bewijs dat stress kanker veroorzaakt.",
      "Sapolsky bekritiseert artsen zoals Bernie Siegel, auteur van Love, Medicine and Miracles, die kanker toeschrijven aan onvoldoende spiritualiteit en beweren dat liefde en moed alleen kunnen genezen. Dat is wreed omdat het de patiënt de schuld geeft van een ongeneeslijke ziekte: wie overlijdt, zou niet genoeg hebben willen leven of niet genoeg hebben liefgehad. Kanker is een uiterst ingewikkeld biologisch probleem, geen straf voor een verkeerde psychologische houding.",
      "5. Een historische tragedie: status thymicolymphaticus",
      "Het hoofdstuk eindigt met een medische ramp door het negeren van stress. Negentiende-eeuwse artsen onderzochten overleden baby’s uit arme gezinnen, bij wie chronische stress de thymus had doen krimpen, en beschouwden een kleine thymus als normaal. Wanneer een kind uit een rijk gezin aan wiegendood overleed, leidde een gezonde, grotere thymus tot de diagnose van een verzonnen ziekte: status thymicolymphaticus. Artsen dachten dat de gezonde thymus de luchtpijp dichtdrukte en schreven op grote schaal bestraling van de hals voor. Dat veroorzaakte in de twintigste eeuw tienduizenden gevallen van schildklierkanker, doordat men niet begreep hoe stress en armoede de anatomie beïnvloeden.",
      "Conclusie van het hoofdstuk: Onze afweer is afgestemd op korte stresscrises, maar kwetsbaar voor chronische zorgen. Tegelijk moeten we extremen vermijden en niet alle menselijke ziekten uitsluitend aan psychologische stress toeschrijven."
    ],
    "9": [
      "Het negende hoofdstuk, ‘Stress en pijn’, begint met de vraag waarom pijn eigenlijk nodig is. Sapolsky legt uit dat pijn een onmisbaar waarschuwingssignaal is. Mensen met pijnasymbolie, hier beschreven als een aangeboren onvermogen om pijn te voelen, leven in een gevaarlijke wereld en raken vaak ernstig gewond omdat hun lichaam geen gevaar meldt.",
      "Dit zijn de belangrijkste begrippen en mechanismen:",
      "1. De werking van pijn: snelle en langzame vezels",
      "Pijninformatie bereikt het ruggenmerg via twee soorten zenuwvezels:",
      "* Snelle vezels reageren onmiddellijk en laten ons abrupt bewegen om aan de pijnbron te ontsnappen, bijvoorbeeld door een hand terug te trekken van iets heets.",
      "* Langzame vezels zorgen voor langdurige, kloppende pijn. Ze moeten ons stilhouden totdat een wond geneest. Prikkeling van snelle vezels kan langzame vezels tijdelijk uitschakelen. Daarom wrijven we instinctief over een gekneusde plek of krabben we aan een insectenbeet om kloppende pijn te verlichten. Als dit mechanisme uitvalt, zoals bij diabetes, kunnen de langzame vezels niet worden uitgeschakeld en wordt zelfs licht ongemak aanhoudende pijn.",
      "2. De subjectiviteit van pijn en de hersenen",
      "De hersenen ontvangen pijnsignalen niet passief, maar interpreteren ze afhankelijk van de context. Een zwaargewonde soldaat vraagt soms veel minder vaak om pijnstillers dan een burger met hetzelfde letsel in vredestijd. Onderzoek liet ook zien dat patiënten met uitzicht op bomen minder pijnstillers nodig hadden dan patiënten die op een kale muur uitkeken.",
      "3. Pijnstilling door stress: analgesie",
      "Bij acute stress —in een gevecht, tijdens het vluchten voor een roofdier of bij sport— kan het lichaam pijn tijdelijk volledig blokkeren. Het maakt lichaamseigen opioïden vrij, zoals endorfinen en enkefalinen. Deze binden aan receptoren in hersenen en ruggenmerg en onderbreken pijnsignalen.",
      "* Dit mechanisme verklaart de bekende runner’s high en een groot deel van de werking van acupunctuur.",
      "* Het placebo-effect werkt ook via het vrijkomen van opioïden in de hersenen. Een middel dat opioïdreceptoren blokkeert, zoals naloxon, laat het placebo-effect verdwijnen.",
      "4. Verhoogde pijngevoeligheid door stress",
      "Soms maakt stress ons juist gevoeliger voor pijn. Het lichamelijke signaal wordt niet sterker, maar de emotionele reactie verandert. De amygdala, betrokken bij angst, speelt hierin een hoofdrol: dezelfde gewaarwording voelt door angst pijnlijker. Sapolsky bespreekt fibromyalgie, een raadselachtig chronisch pijnsyndroom. Artsen beschouwden dit lang als een zuiver psychosomatische neurose, maar latere gegevens tonen meer activiteit in emotionele hersencentra, veranderde glucocorticoïdengehalten en meer van een pijnsignaalstof in het hersenvocht.",
      "5. Chronische stress en uitputting",
      "Sapolsky benadrukt een bijzondere eigenschap van het pijnstillingssysteem. Anders dan stressreacties zoals hormoonproductie, die te lang kunnen doorgaan en het lichaam beschadigen, kan stressanalgesie niet eindeloos werken. Langdurige stress put de voorraad lichaamseigen opioïden snel uit. Pijnstilling is dus een tijdelijke noodmaatregel. Als de stress niet stopt, keert de pijn onvermijdelijk terug."
    ],
    "10": [
      "Stel je voor: je herinnert je elk detail van de dag waarop je hoorde dat de Twin Towers waren ingestort, of de seconden waarin je net een auto-ongeluk ontliep, maar niet wat je twee dagen geleden ontbeet. Hoofdstuk tien, ‘Stress en geheugen’, onderzoekt deze paradox: waarom stress het geheugen uitzonderlijk kan verscherpen of juist afbreken.",
      "1. De architectuur van het geheugen",
      "Sapolsky legt eerst uit dat geheugen geen enkelvoudig systeem is. Een belangrijk onderscheid bestaat tussen expliciet, declaratief geheugen —feiten, gebeurtenissen en namen— en impliciet, procedureel geheugen —vaardigheden zoals fietsen of tennissen—. De hippocampus speelt een centrale rol in expliciet geheugen.",
      "Herinneringen zitten niet in afzonderlijke neuronen, maar zijn verdeeld over uitgebreide netwerken. Leren ontstaat wanneer synapsen, met hulp van de neurotransmitter glutamaat, een niet-lineaire prikkeldrempel overschrijden en een inzichtmoment ontstaat.",
      "2. Hoe stress het geheugen verbetert: de omgekeerde U",
      "Het verband tussen stress en geheugen heeft de vorm van een omgekeerde U. Korte, matige stress ligt op het stijgende deel en verbetert geheugen en concentratie.",
      "Het sympathische zenuwstelsel maakt adrenaline en noradrenaline vrij. Een matig glucocorticoïdengehalte verhoogt de glucosetoevoer naar de hersenen en geeft neuronen meer energie. Zintuiglijke receptoren worden gevoeliger en emotionele gebeurtenissen branden zich in het geheugen. Evolutionair is dit essentieel: bij gevaar moeten we onthouden hoe we erin terechtkwamen en hoe we eruit komen.",
      "3. Chronische stress als afbreker",
      "Als stress te sterk wordt of maanden duurt, daalt de curve snel. Het geheugen, vooral het ophalen van eerdere informatie, begint te haperen. Dat is duidelijk bij patiënten met het syndroom van Cushing, waarbij te veel stresshormonen ontstaan, en bij mensen die langdurig synthetische glucocorticoïden gebruiken.",
      "Chronische stress schaadt de hippocampus op meerdere niveaus:",
      "* Minder verbindingen: Uitlopers van neuronen, axonen en dendrieten, verschrompelen en verzwakken. Synaptische netwerken worden minder complex. Herinneringen verdwijnen niet, maar zijn moeilijker bereikbaar.",
      "* Geremde neurogenese: Lang dacht men dat volwassen hersenen geen nieuwe cellen maakten, maar dit proces werd in de hippocampus gevonden. Stress en glucocorticoïden remmen de vorming van nieuwe neuronen sterk.",
      "* Energietekort en celdood: Na ongeveer 30 minuten onafgebroken stress begint de glucosetoevoer naar de hippocampus te dalen, tot wel 25%. Neuronen met energietekort zijn bijzonder kwetsbaar: een beroerte of klein letsel doodt dan meer cellen. Zeer langdurige blootstelling aan hoge stresshormoonspiegels kan hippocampusneuronen doden door glucocorticoïd-neurotoxiciteit.",
      "4. Fysieke hersenkrimp bij mensen",
      "Het hoofdstuk eindigt met verontrustende bevindingen die dieronderzoek uitbreiden naar mensen. MRI-onderzoek laat zien dat aandoeningen met ernstige chronische stress gepaard kunnen gaan met een kleinere hippocampus. Dit wordt gezien bij posttraumatische stressstoornis, langdurige ernstige depressie, cabinepersoneel dat vaak tijdzones doorkruist en chronisch verstoorde biologische ritmes heeft, en bij normale veroudering wanneer cortisol met de jaren stijgt.",
      "Conclusie van het hoofdstuk: Matige stress helpt de hersenen goed te presteren en belangrijke ervaringen vast te leggen. Maar als psychologische zorgen dit noodsysteem dagen en maanden actief houden, kunnen neurale netwerken krimpen en achteruitgaan, waardoor onze herinneringen moeilijker bereikbaar worden."
    ]
  },
  "ru": {
    "5": [
      "Пятая глава книги, озаглавленная «Язва, гонка в саванне и горячий шоколад», посвящена сложным взаимоотношениям между стрессом, нашим аппетитом, пищеварением и возникновением язвенной болезни.",
      "Вот основные идеи главы:",
      "1. Стресс и потребление пищи: почему мы едим (или не едим)",
      "Стресс коренным образом меняет наше пищевое поведение, но делает это неодинаково для всех: две трети людей в стрессе начинают есть больше, а одна треть — меньше. Это объясняется соревнованием двух гормонов:",
      "* КРГ (кортикотропин-рилизинг-гормон): выделяется в первые секунды стресса и подавляет аппетит, чтобы организм не тратил силы на еду во время бегства от льва.",
      "* Глюкокортикоиды: действуют медленнее (минуты и часы) и, наоборот, стимулируют аппетит, помогая организму восстановить запасы энергии после кризиса.",
      "* Итог: Если стресс кратковременный и сильный, побеждает КРГ и аппетит исчезает. Если же человек испытывает частые мелкие стрессы в течение дня («хронический психологический стресс»), уровень глюкокортикоидов в крови остается стабильно высоким, что заставляет его постоянно что-то жевать.",
      "2. «Яблоки» и «груши»: куда уходит жир",
      "Глюкокортикоиды не просто повышают аппетит, они диктуют организму, где именно запасать жир. Они стимулируют накопление жира в брюшной области, превращая человека в «яблоко».",
      "* Брюшной жир гораздо опаснее для здоровья, так как он легче попадает в печень, повышая риск диабета и болезней сердца.",
      "* Интересный факт: потребление «утешительной еды» (жирного и сладкого) и накопление брюшного жира действительно снижают силу стрессовой реакции мозга, помогая человеку чувствовать себя лучше, но за счет вреда здоровью.",
      "3. Стресс и работа кишечника",
      "Во время острого стресса пищеварение полностью отключается, так как это очень энергозатратный процесс (на него уходит 10–20% всей энергии).",
      "* Почему тогда от страха случается диарея? Организм стремится сбросить «лишний вес», чтобы бежать быстрее. Тонкий кишечник замирает, а толстый начинает активно сокращаться, выбрасывая содержимое до того, как из него успеет всосаться вода.",
      "* Синдром раздраженного кишечника (СРК): Это функциональное расстройство, которое очень чувствительно к стрессу. Стресс делает кишечник гиперчувствительным к боли, а травмы, пережитые в раннем детстве, могут навсегда сделать этот орган уязвимым.",
      "4. Загадка язвы желудка",
      "Долгое время считалось, что язву вызывает только стресс. Затем в 1980-х годах открыли бактерию Helicobacter pylori, и медицина бросилась в другую крайность, заявив, что стресс ни при чем. Сапольски объясняет, что правда посередине: бактерия — это «заряженный пистолет», но именно стресс «нажимает на курок».",
      "Как стресс вызывает язву (основные механизмы):",
      "1. Кислотный рикошет: Во время стресса защита желудка (слизь и бикарбонат) ослабевает для экономии энергии. Когда стресс заканчивается, выработка кислоты возобновляется мгновенно, а защита восстанавливается медленно. Именно в этот период восстановления желудок начинает переваривать сам себя.",
      "2. Снижение кровоснабжения: Из-за недостатка крови в стенках желудка возникают микроинфаркты.",
      "3. Свободные радикалы: В момент возвращения крови в желудок после стресса выделяются опасные вещества, разрушающие клетки.",
      "4. Подавление иммунитета: Хронический стресс мешает организму сдерживать размножение Helicobacter pylori.",
      "Итог главы: Наш желудочно-кишечный тракт — тонкий инструмент, который первым реагирует на наши мысли. Мы заболеваем язвой не из-за того, что на нас напал лев, а из-за того, что слишком часто «нажимаем на тормоза» и «бьем по газам» своего пищеварения в ответ на психологические проблемы."
    ],
    "6": [
      "Шестая глава книги, озаглавленная «Карликовость и роль матери», посвящена тому, как стресс и эмоциональная среда влияют на процессы роста организма, начиная с эмбрионального периода и заканчивая взрослой жизнью.",
      "1. Пренатальный стресс и метаболическое программирование",
      "Стресс, пережитый матерью во время беременности, накладывает отпечаток на всю жизнь ребенка. Этот процесс называют метаболическим программированием.",
      "* «Бережливый» метаболизм: Если эмбрион получает сигналы о голоде или высоком уровне стресса (через глюкокортикоиды матери), его организм учится максимально эффективно запасать питательные вещества.",
      "* Последствия: Во взрослом возрасте такие люди имеют повышенный риск гипертонии, ожирения, диабета 2-го типа и сердечно-сосудистых заболеваний.",
      "* Мозг и поведение: Пренатальный стресс может приводить к уменьшению размера головы при рождении, повышенной тревожности (из-за изменений в миндалевидном теле) и ухудшению памяти в старости.",
      "* Передача через поколения: Эффекты стресса могут передаваться внукам без участия генов — через общую кровеносную систему матери и плода.",
      "2. Психосоциальная карликовость",
      "Самым ярким примером влияния психологического стресса на рост является стрессогенная карликовость.",
      "* Суть явления: Дети, находящиеся в условиях тяжелого эмоционального стресса или лишенные любви, перестают расти, несмотря на достаточное питание. У них фиксируется критически низкий уровень соматотропина (гормона роста).",
      "* Механизмы: Помимо низкого уровня гормона роста, избыточная активность симпатической системы мешает кишечнику нормально абсорбировать питательные вещества.",
      "* Обратимость: Если устранить источник стресса (например, сменить окружение или медперсонал, к которому ребенок привязан), рост может восстановиться невероятными темпами.",
      "3. Роль материнской заботы и тактильного контакта",
      "Источники подчеркивают, что для нормального развития организма необходима «любовь» в биологическом смысле — стимуляция и прикосновения.",
      "* Эксперименты Харлоу: Опыты на макаках-резусах с искусственными «матерями» доказали, что детеныши выбирают не ту «мать», которая кормит, а ту, которая мягкая и к которой можно прижаться.",
      "* Недоношенные дети: Исследования Тиффани Филд показали, что всего 15 минут поглаживаний трижды в день заставляют недоношенных младенцев расти на 50% быстрее и развиваться активнее.",
      "* Последствия депривации: Лишение материнской заботы у животных приводит к пожизненному повышению уровня глюкокортикоидов и замедлению развития отделов мозга, отвечающих за обучение и память.",
      "4. Функция роста у взрослых",
      "Хотя взрослые люди больше не увеличиваются в росте, соматотропин продолжает вырабатываться в их организме.",
      "* Ремонт костей: У взрослых гормон роста отвечает за постоянное обновление костной ткани и «заделывание трещин» в фундаменте организма.",
      "* Стресс и остеопороз: Хронический стресс и избыток глюкокортикоидов блокируют этот процесс обновления, что может привести к развитию остеопороза и атрофии скелета.",
      "Итог главы: Рост — это не только вопрос калорий, но и вопрос психологического благополучия. Отсутствие тактильного контакта и эмоциональной поддержки является мощнейшим биологическим стрессором, способным «выключить» систему роста и нанести непоправимый вред здоровью на десятилетия вперед."
    ],
    "7": [
      "Седьмая глава книги, озаглавленная «Секс и репродуктивная система», раскрывает, почему во время стресса наш организм рассматривает размножение как непозволительную роскошь, отключая сексуальное влечение и репродуктивные функции ради спасения жизни.",
      "Вот основные идеи этой главы:",
      "1. Мужская физиология: тестостерон и загадка эрекции",
      "Во время стресса выработка тестостерона у мужчин резко падает. Организм блокирует этот процесс на всех уровнях: эндорфины отключают сигналы в мозге, пролактин снижает чувствительность гипофиза, а глюкокортикоиды блокируют реакцию яичек. Но еще более драматично стресс влияет на механику секса.",
      "* Парасимпатика и симпатика: Нормальная эрекция возможна только при активной парасимпатической нервной системе (которая отвечает за покой и расслабление). Эякуляция же запускается симпатической нервной системой (реакция «нападай или убегай»).",
      "* Стресс ломает систему: Если вы находитесь в состоянии хронического стресса, ваша симпатическая система активна, а парасимпатическая подавлена — возникает импотенция (неспособность достичь эрекции). Если же эрекция уже есть, но внезапно возникает стрессовая мысль, система слишком быстро переключается на симпатику, что приводит к преждевременной эякуляции. (Исключением в природе являются гиены: у их самцов эрекция парадоксальным образом возникает именно в моменты стресса и социального подчинения, как сигнал покорности агрессивным самкам).",
      "2. Женская физиология: истощение, пролактин и либидо",
      "Женская репродуктивная система не менее уязвима к физическим и психологическим кризисам.",
      "* Жир и эстроген: В женском организме небольшое количество мужских гормонов (андрогенов) вырабатывается надпочечниками, а затем ферменты в жировых клетках превращают их в эстрогены. Если из-за стресса, голодания или изнурительных тренировок (например, у балерин или бегуний) количество жира критически снижается, андрогены накапливаются, и менструальный цикл нарушается или полностью прекращается.",
      "* Пролактин и контрацепция: Во время стресса выделяется гормон пролактин, который сильно подавляет репродуктивную функцию. Этот же гормон вырабатывается при грудном вскармливании. Сапольски приводит в пример бушменов Калахари: их женщины кормят детей грудью на протяжении трех лет по несколько раз в час, поддерживая стабильно высокий уровень пролактина, что работает как надежное природное противозачаточное средство.",
      "* Потеря либидо: Стресс подавляет выработку надпочечниковых андрогенов и эстрогенов, что напрямую ведет к снижению сексуального влечения у женщин.",
      "3. ЭКО и прерывание беременности",
      "* Стресс от лечения: Процедуры экстракорпорального оплодотворения (ЭКО) сами по себе вызывают колоссальный стресс у женщин из-за болезненных инъекций, гормональных скачков и тревожного ожидания. Чем выше уровень стресса (и глюкокортикоидов) в ходе цикла ЭКО, тем ниже вероятность успешного результата.",
      "* Риск выкидыша: Сильный психологический стресс может привести к прерыванию беременности. Во время кризиса симпатическая нервная система сужает кровеносные сосуды, уменьшая приток крови к матке. Если это происходит часто, плод может пострадать от гипоксии (нехватки кислорода).",
      "Итог главы",
      "Стресс способен сломать репродуктивную систему множеством способов. Однако базовая, примитивная тяга к размножению невероятно устойчива — исследования показывают, что даже в чудовищных условиях концлагерей примерно у половины женщин сохранялся менструальный цикл. Биологический рефлекс продолжения рода выдерживает колоссальные нагрузки. Тем не менее, тонкие нюансы сексуальности — либидо, романтическое влечение, удовольствие и расслабление — крайне хрупки и легко разрушаются повседневным психологическим стрессом."
    ],
    "8": [
      "Восьмая глава книги, озаглавленная «Иммунитет, стресс и болезни», погружает нас в новую область науки — психонейроиммунологию, изучающую поразительные связи между нашими мыслями, мозгом и иммунной защитой.",
      "Эта глава разрушает многие популярные мифы о стрессе и болезнях, объясняя, как именно мы становимся уязвимыми перед инфекциями и почему «позитивное мышление» не лечит рак. Вот основные концепции главы:",
      "1. Иммунные качели: сюрприз для ученых",
      "Долгое время считалось, что стресс просто подавляет иммунитет ради экономии энергии. Однако недавние открытия показали, что реакция организма гораздо сложнее:",
      "* Фаза активации: В первые 30 минут стресса иммунитет не падает, а, наоборот, резко усиливается. Гормоны стресса (включая глюкокортикоиды и адреналин) не дезактивируют иммунные клетки, а срочно отправляют их из крови на «передовую» — например, в кожу, чтобы организм быстрее заживлял раны в случае травмы.",
      "* Фаза подавления: Если стресс затягивается, глюкокортикоиды начинают целенаправленно уничтожать лимфоциты (иммунные клетки), причем убивают в первую очередь самые старые и бесполезные из них.",
      "* Зачем нужно подавление? Ученый Аллан Мунк выяснил, что организм «тормозит» иммунную систему после первоначальной мобилизации специально для того, чтобы она не перестаралась. Если не выключить гиперактивный иммунитет, он начнет путать свои ткани с чужими, что приведет к аутоиммунным заболеваниям (таким как рассеянный склероз или ревматоидный артрит). Если эта система «торможения» дает сбой, риск аутоиммунных болезней возрастает.",
      "2. Маршруты болезней",
      "Почему в состоянии стресса мы чаще болеем? Сапольски предлагает разделять два пути:",
      "* Психонейроиммунный маршрут: Стресс вызывает выброс гормонов, которые физиологически подавляют иммунитет и повышают вероятность инфекций.",
      "* Маршрут образа жизни: В состоянии стресса или депрессии люди хуже спят, плохо питаются, забывают принять лекарство или надеть теплое пальто в мороз. Часто именно изменение образа жизни из-за стресса, а не сами гормоны, является истинной причиной болезни.",
      "3. Простуда, герпес и коварство вирусов",
      "* Простудные заболевания: Эпидемиологические данные и эксперименты подтверждают, что хронический стресс действительно повышает риск подхватить обычную простуду.",
      "* Латентные вирусы: Вирусы герпеса прячутся в нервных клетках и годами ждут удобного момента для размножения. Как они узнают, что ваш иммунитет ослаб? Оказывается, в их ДНК есть специальный «датчик», который реагирует на повышение уровня глюкокортикоидов в вашей крови. Более того, герпес способен на невероятный трюк: он сам заставляет ваш гипоталамус вырабатывать гормоны стресса, чтобы создать себе идеальные условия для обострения болезни.",
      "4. Рак и мифология «чудесных исцелений»",
      "Пожалуй, самая острая часть главы посвящена связи стресса и онкологии. У животных сильный стресс действительно может ускорять рост уже существующих опухолей, так как глюкокортикоиды способствуют прорастанию кровеносных сосудов в опухоль (ангиогенезу) и снабжают её глюкозой. Однако у людей надежных доказательств того, что стресс вызывает рак, не существует.",
      "Сапольски жестко и аргументированно критикует врачей вроде Берни Зигеля (автора книги «Любовь, медицина и чудеса»), которые утверждают, что рак возникает из-за недостатка духовности и лечится одной лишь любовью и смелостью. Подобный подход крайне жесток, так как перекладывает вину за неизлечимую болезнь на жертву: если пациент умер, значит, он якобы «недостаточно сильно хотел жить» или «мало любил». На самом деле, рак — это сложнейшая биологическая проблема, и он не является наказанием за неверный психологический настрой.",
      "5. Исторический гротеск: статус тимиколимфатикус",
      "Завершает главу трагическая история о том, как игнорирование стресса привело к медицинской катастрофе. В XIX веке врачи, вскрывая трупы младенцев из бедных семей (постоянно живших в стрессе, из-за чего их тимус — вилочковая железа — был сморщенным), решили, что такой крошечный тимус является нормой. Когда же от синдрома внезапной детской смертности умирал ребенок из богатой семьи (не знавший стресса и имевший нормальный, крупный тимус), врачи ставили диагноз — воображаемую болезнь status thymicolymphaticus. Посчитав, что здоровый тимус давит на трахею, младенцам стали массово назначать радиационное облучение шеи. Это привело к десяткам тысяч случаев рака щитовидной железы в XX веке из-за банального непонимания врачами того, как стресс и бедность влияют на анатомию.",
      "Итог главы: Наш иммунитет тонко настроен на короткие стрессовые кризисы, но уязвим перед хроническими тревогами. В то же время важно избегать крайностей и не списывать все недуги человечества исключительно на психологический стресс."
    ],
    "9": [
      "Девятая глава книги, озаглавленная «Стресс и боль», начинается с философского размышления о том, зачем вообще нужна боль. Сапольски объясняет, что боль — это жизненно важный сигнал, предупреждающий об опасности. Люди, страдающие болевой асимболией (врожденной неспособностью чувствовать боль), живут в крайне опасном мире и часто получают тяжелейшие травмы, просто потому что их тело не сигнализирует об угрозе.",
      "Вот основные концепции и механизмы, описанные в этой главе:",
      "1. Механика боли: быстрые и медленные волокна",
      "Информация о боли передается в спинной мозг по двум типам нервных волокон:",
      "* Быстрые волокна реагируют мгновенно и заставляют нас совершать резкие движения, чтобы спастись от источника боли (например, отдернуть руку от горячего).",
      "* Медленные волокна отвечают за длительную, пульсирующую боль. Их задача — заставить нас сохранять неподвижность, пока рана не заживет. Интересно, что стимуляция быстрых волокон может временно «отключить» медленные. Именно поэтому мы инстинктивно растираем ушибленное место или чешем укус насекомого, чтобы снять пульсирующую боль. Если этот механизм ломается (как, например, при диабете), то человек не может отключить медленные волокна, и даже легкий дискомфорт превращается в постоянную боль.",
      "2. Субъективность боли и роль мозга",
      "Мозг не просто пассивно принимает сигналы о боли, он активно их интерпретирует в зависимости от контекста. Например, тяжело раненный солдат на поле боя может требовать обезболивающего гораздо реже, чем гражданский с такой же травмой в мирное время. Также исследования показали, что пациенты, в палатах которых есть окно с видом на деревья, требуют меньше обезболивающих препаратов, чем те, кто смотрит на глухую стену.",
      "3. Обезболивание, вызванное стрессом (анальгезия)",
      "В моменты острого стресса (например, в пылу сражения, при бегстве от хищника или во время спортивных соревнований) организм способен на время полностью блокировать боль. Это происходит благодаря выбросу эндогенных опиоидов (эндорфинов и энкефалинов), которые связываются с рецепторами в мозге и спинном мозге, перекрывая болевые сигналы.",
      "* Именно этот механизм объясняет знаменитую «эйфорию бегуна» и во многом раскрывает принцип действия акупунктуры (иглоукалывания).",
      "* Эффект плацебо также работает через выделение мозгом опиоидов. Если человеку дать препарат, блокирующий опиатные рецепторы (налоксон), плацебо перестает действовать.",
      "4. Стрессогенная гиперчувствительность к боли",
      "Иногда стресс действует наоборот, делая нас более уязвимыми к боли. При этом физически сама боль не усиливается, меняется наша эмоциональная реакция на нее. В этом процессе ключевую роль играет миндалевидное тело (центр страха и тревоги в мозге). Мы просто интерпретируем те же самые ощущения как более мучительные из-за тревоги. В связи с этим автор упоминает фибромиалгию — таинственный синдром хронической боли. Долгое время врачи считали его исключительно психосоматическим неврозом, но современные данные показывают, что у таких пациентов повышена активность эмоциональных центров мозга, нарушен уровень глюкокортикоидов и повышена концентрация вещества-посредника боли в спинномозговой жидкости.",
      "5. Цена хронического стресса и истощение",
      "Сапольски отмечает уникальную особенность обезболивающей системы. В отличие от многих других стрессовых реакций (например, выработки гормонов, которые не отключаются вовремя и в итоге наносят вред организму), механизм стрессогенного обезболивания просто не может работать вечно. При длительном стрессе запасы эндогенных опиоидов быстро истощаются. Это означает, что обезболивание — лишь временная мера, предназначенная для экстренного спасения. Если стресс не прекращается, боль неизбежно возвращается."
    ],
    "10": [
      "Представьте себе: вы помните в мельчайших деталях день, когда узнали о падении башен-близнецов, или секунды, когда чудом избежали автомобильной аварии, но совершенно не можете вспомнить, что ели на завтрак пару дней назад. Десятая глава книги, озаглавленная «Стресс и память», раскрывает именно этот парадокс: почему стресс может феноменально обострять нашу способность запоминать, а может полностью ее разрушать.",
      "1. Архитектура памяти",
      "Сапольски начинает с объяснения того, что память не монолитна. Главное различие проходит между эксплицитной (декларативной) памятью (факты, события, имена) и имплицитной (процедурной) памятью (навыки, такие как езда на велосипеде или игра в теннис). За эксплицитную память отвечает особый отдел мозга — гиппокамп.",
      "Воспоминания не хранятся в одиночных нейронах, они распределены в обширных нейронных сетях. Обучение происходит тогда, когда в синапсах преодолевается нелинейный порог возбуждения (благодаря нейромедиатору глутамату) и возникает «момент озарения».",
      "2. Как стресс улучшает память (перевернутая U)",
      "Взаимосвязь между стрессом и памятью описывается в виде перевернутой буквы U. Кратковременный, умеренный стресс находится на восходящей дуге — он улучшает память и концентрацию.",
      "В этот момент симпатическая нервная система выбрасывает адреналин и норадреналин, а умеренный уровень глюкокортикоидов увеличивает приток глюкозы к мозгу, давая нейронам больше энергии. Чувствительность сенсорных рецепторов повышается, и эмоционально заряженные события буквально «выжигаются» в нашей памяти. С эволюционной точки зрения это жизненно необходимо: столкнувшись с угрозой, нам важно навсегда запомнить, как мы в нее попали и как из нее выбраться.",
      "3. Хронический стресс как разрушитель",
      "Но если стресс становится слишком сильным или затягивается на месяцы, кривая перевернутой U стремительно ползет вниз: память (особенно функция извлечения информации из прошлого) начинает отказывать. Это отчетливо видно на примере пациентов с синдромом Кушинга (болезнью, вызывающей выброс тонн гормонов стресса) или людей, длительно принимающих синтетические глюкокортикоиды.",
      "Хронический стресс наносит гиппокампу многоуровневый урон:",
      "* Потеря связности: Отростки нейронов (аксоны и дендриты) начинают усыхать и истощаться, синаптические сети теряют сложность. Сами воспоминания никуда не исчезают, но к ним становится гораздо труднее получить доступ.",
      "* Остановка нейрогенеза: Долгое время считалось, что мозг взрослых не создает новые клетки, но выяснилось, что в гиппокампе этот процесс идет. Однако стресс и глюкокортикоиды являются мощнейшими ингибиторами (подавителями) рождения новых нейронов.",
      "* Энергетический голод и гибель клеток: Примерно через 30 минут непрерывного стресса приток глюкозы к гиппокампу начинает падать (снижение доходит до 25%). В таком обесточенном состоянии нейроны становятся крайне уязвимыми: если в этот момент произойдет инсульт или микротравма, клеток погибнет гораздо больше. При очень длительном воздействии высоких доз гормонов стресса нейроны гиппокампа могут буквально погибать от так называемой нейротоксичности глюкокортикоидов.",
      "4. Физическое уменьшение мозга у людей",
      "Глава завершается тревожными фактами, перенесенными с лабораторных крыс на людей. Исследования МРТ показывают, что состояния, связанные с хроническим тяжелым стрессом, могут приводить к физическому уменьшению объема гиппокампа. Такая атрофия наблюдается при посттравматическом стрессовом расстройстве (ПТСР), затяжной большой депрессии, длительной работе с частой сменой часовых поясов у стюардесс (хронический сбой биоритмов), а также при нормативном старении у тех пожилых людей, чей уровень кортизола с годами повышается.",
      "Итог главы: Умеренный стресс — наш союзник, который заставляет мозг работать на пике возможностей и фиксировать важный опыт. Но если заставлять эту аварийную систему работать сутками и месяцами из-за чисто психологических переживаний, наши нейронные сети начнут в буквальном смысле усыхать и распадаться, лишая нас доступа к собственным воспоминаниям."
    ]
  }
};
