import type { Language } from "@/lib/site-content";
import { chapterOneTranslations } from "./chapter-one-translations";
import { fullChapterSummaries } from "./full-chapter-summaries";
import { moreChapterSummaries } from "./more-chapter-summaries";
import { additionalChapterCards } from "./additional-chapter-cards";
import { finalChapterSummaries } from "./final-chapter-summaries";
import { finalChapterCards } from "./final-chapter-cards";

type Chapter = {
  number: number;
  title: string;
  summary: string;
  points: string[];
  terms: string;
  question: string;
  fullText?: string[];
};

type BookCopy = {
  eyebrow: string;
  title: string;
  subtitle: string;
  intro: string;
  chaptersLabel: string;
  keyIdeas: string;
  termsLabel: string;
  questionLabel: string;
  fullTextLabel: string;
  note: string;
  chapters: Chapter[];
};

export const sapolskyContent: Record<Language, BookCopy> = {
  ru: {
    eyebrow: "КНИЖНЫЙ КЛУБ · РОБЕРТ САПОЛЬСКИ",
    title: "Почему у зебр не бывает инфаркта",
    subtitle: "Психология и физиология стресса — конспект по главам",
    intro: "Этот раздел соединяет идеи Сапольского с психобиологией: от быстрой реакции «бей или беги» до влияния хронического стресса на сердце, обмен веществ, пищеварение, рост, репродукцию и иммунитет.",
    chaptersLabel: "Готовые главы · 1–8",
    keyIdeas: "Главные идеи",
    termsLabel: "Термины · ES · EN",
    questionLabel: "Вопрос для размышления",
    fullTextLabel: "Полное резюме главы",
    note: "Авторский учебный конспект Sensus Vitae. Это краткое изложение идей книги, а не замена оригинального текста и не медицинская рекомендация.",
    chapters: [
      {number:1,title:"Почему у зебр не бывает язв?",summary:"Острая стрессовая реакция спасает при непосредственной угрозе. Проблема человека в том, что тот же механизм может включаться из-за мыслей, ожиданий и конфликтов — и оставаться активным слишком долго.",points:["Энергия быстро направляется мышцам, сердцу и мозгу.","Пищеварение, рост, восстановление и репродукция временно откладываются.","Хроническая активация увеличивает вероятность болезни, но не является её единственной причиной."],terms:"реакция на стресс · respuesta de estrés · stress response; аллостаз · alostasis · allostasis",question:"Какие мои стрессоры требуют действия прямо сейчас, а какие существуют преимущественно в мыслях?",fullText:[
        "Представьте себе два часа ночи. Вы лежите в постели, покрываясь липким потом от мыслей о завтрашнем экзамене или важном отчёте. В этот момент ваш мозг совершает удивительное и одновременно жестокое путешествие: от страха провалить карьеру он переходит к уверенности, что у вас смертельная опухоль, оправдывающая вашу панику. Это — мир человеческого стресса.",
        "А теперь перенесёмся в саванну. Там зебра несётся изо всех сил, чтобы не стать обедом льва, а лев бежит так же быстро, чтобы не умереть с голода. Для них стресс — это острый физический кризис, длящийся считанные минуты. Если зебра спаслась, её организм немедленно возвращается в состояние покоя.",
        "В этом и заключается главная трагедия человека, описанная в первой главе: наши тела обладают великолепным механизмом адаптации, предназначенным для того, чтобы спасти шкуру в короткой гонке по саванне. Однако мы, будучи «достаточно умными», научились запускать эту мощную систему просто силой мысли, переживая из-за ипотеки или социального статуса.",
        "Если гомеостаз — это поддержание оптимального уровня кислорода или температуры, то аллостаз — сложная координация всего организма ради достижения баланса. Проблема в том, что мы заставляем «слонов стресса» запрыгивать на качели нашего внутреннего равновесия слишком часто.",
        "Зебра не страдает от язвы желудка потому, что не умеет предчувствовать стресс за месяцы до его наступления. Человек же может заболеть именно потому, что активирует систему экстренного спасения на недели и месяцы. Реакция на стресс в итоге становится более разрушительной, чем сам стрессор.",
        "История науки в этой главе показана через опыты Ганса Селье — «отца стресса», который, будучи не самым ловким лаборантом, гонялся за крысами с веником. Он обнаружил, что независимо от воздействия организм выдаёт сходную неспецифическую реакцию: язву, увеличенные надпочечники и атрофию иммунной системы.",
        "Итог главы: мы живём достаточно долго и благополучно, чтобы страдать не только от инфекций или голода, но и от болезней, связанных с хроническим беспокойством. Мы — существа, способные довести себя до болезни, просто думая о будущем."
      ]},
      {number:2,title:"Железы, мурашки и гормоны",summary:"Мозг координирует стресс через автономную нервную систему и гормональные оси. Быстрый путь связан с адреналином, более медленный — с осью гипоталамус–гипофиз–надпочечники и глюкокортикоидами.",points:["Симпатическая система мобилизует организм, парасимпатическая помогает восстановлению.","Адреналин действует быстро; глюкокортикоиды поддерживают реакцию дольше.","Здоровая система должна не только включаться, но и вовремя выключаться."],terms:"ВНС · sistema nervioso autónomo · autonomic nervous system; ось HPA · eje HHA · HPA axis",question:"Что помогает моему организму почувствовать, что опасность уже закончилась?"},
      {number:3,title:"Инсульты, инфаркты и смерть вуду",summary:"Во время стресса сердце работает интенсивнее, давление повышается, а сосуды перераспределяют кровоток. Если это повторяется постоянно, адаптивная реакция превращается в нагрузку на сердечно-сосудистую систему.",points:["Хронически повышенное давление повреждает стенки сосудов.","В местах повреждения легче развивается воспаление и атеросклероз.","Стресс взаимодействует с другими факторами риска, а не действует изолированно."],terms:"гипертония · hipertensión · hypertension; атеросклероз · aterosclerosis · atherosclerosis",question:"Какие регулярные привычки помогают моему телу завершать стрессовую реакцию?"},
      {number:4,title:"Стресс, обмен веществ и ликвидация активов",summary:"При угрозе организм быстро высвобождает глюкозу и жирные кислоты — топливо для немедленного действия. При хроническом стрессе постоянная мобилизация энергии повышает метаболическую цену адаптации.",points:["Запасы энергии расщепляются вместо долгосрочного накопления и восстановления.","Частые гормональные всплески могут ухудшать чувствительность к инсулину.","Стресс влияет на аппетит по-разному: возможны и его снижение, и тяга к калорийной пище."],terms:"глюкокортикоиды · glucocorticoides · glucocorticoids; инсулинорезистентность · resistencia a la insulina · insulin resistance",question:"Когда я ем после стресса, я отвечаю на голод, усталость или потребность в успокоении?"},
      {number:5,title:"Язвы, кишечник и десерты",summary:"Стресс меняет моторику, секрецию и кровоснабжение пищеварительной системы. Он не объясняет все заболевания ЖКТ, но способен усиливать уязвимость и симптомы, особенно при функциональных расстройствах.",points:["Во время угрозы пищеварение теряет приоритет.","Причины язв сложнее простой формулы «всё от нервов»; важную роль играет Helicobacter pylori.","Связь мозга и кишечника делает симптомы чувствительными к контексту и длительному напряжению."],terms:"ось мозг–кишечник · eje intestino-cerebro · gut–brain axis; функциональное расстройство · trastorno funcional · functional disorder",question:"Какие ситуации усиливают телесные симптомы — и что меняется, когда появляется чувство безопасности?"},
      {number:6,title:"Карликовость и значение матерей",summary:"Рост — долгосрочный проект организма. При длительной угрозе энергия направляется на выживание, а не на рост и восстановление; особенно заметны последствия хронического стресса в раннем развитии.",points:["Гормоны стресса могут подавлять гормон роста и связанные с ним процессы.","Питание важно, но эмоциональная безопасность и забота тоже влияют на развитие.","Ранний опыт не предопределяет судьбу, однако может менять физиологическую чувствительность к стрессу."],terms:"гормон роста · hormona del crecimiento · growth hormone; ранний стресс · estrés temprano · early-life stress",question:"Какие условия помогают человеку не только выживать, но и расти?"},
      {number:7,title:"Секс и репродукция",summary:"Размножение требует энергии и ощущения относительной безопасности. Длительный стресс способен нарушать гормональную регуляцию, снижать либидо и влиять на фертильность у женщин и мужчин.",points:["Стресс может подавлять сигналы гипоталамуса, управляющие репродуктивной осью.","Последствия зависят от длительности, интенсивности и индивидуального контекста.","Психологические ожидания и отношения взаимодействуют с физиологией."],terms:"репродуктивная ось · eje reproductivo · reproductive axis; либидо · libido · libido",question:"Как чувство безопасности, близость и контроль меняют телесную реакцию на стресс?"},
      {number:8,title:"Иммунитет, стресс и болезнь",summary:"Связь между стрессом и иммунитетом не сводится к простому «стресс снижает иммунитет». Краткая реакция может временно мобилизовать защиту, а хроническая — нарушать её регуляцию и поддерживать воспаление.",points:["Иммунная реакция меняется во времени: ранняя активация может сменяться подавлением.","Хронический стресс способен ухудшать заживление и контроль воспаления.","Риск заболевания определяется взаимодействием стресса, биологии, поведения и среды."],terms:"психонейроиммунология · psiconeuroinmunología · psychoneuroimmunology; воспаление · inflamación · inflammation",question:"Почему корректнее говорить, что стресс меняет иммунную регуляцию, а не просто «ослабляет иммунитет»?"}
    ]
  },
  es: {
    eyebrow:"CLUB DE LECTURA · ROBERT SAPOLSKY",title:"¿Por qué las cebras no tienen úlcera?",subtitle:"Psicología y fisiología del estrés, capítulo a capítulo",intro:"Este espacio conecta las ideas de Sapolsky con la psicobiología: desde la respuesta rápida de lucha o huida hasta los efectos del estrés crónico sobre el corazón, el metabolismo, la digestión, el crecimiento, la reproducción y la inmunidad.",chaptersLabel:"Capítulos disponibles · 1–8",keyIdeas:"Ideas principales",termsLabel:"Términos · RU · EN",questionLabel:"Pregunta para reflexionar",fullTextLabel:"Resumen completo del capítulo",note:"Apuntes originales de Sensus Vitae. Este resumen no sustituye el libro ni constituye asesoramiento médico.",
    chapters: [
      {number:1,title:"¿Por qué las cebras no tienen úlcera?",summary:"La respuesta aguda al estrés puede salvarnos ante una amenaza inmediata. En los seres humanos, el mismo mecanismo puede activarse por pensamientos, expectativas y conflictos, y mantenerse durante demasiado tiempo.",points:["La energía se dirige rápidamente a los músculos, el corazón y el cerebro.","La digestión, el crecimiento, la reparación y la reproducción se aplazan.","La activación crónica aumenta la vulnerabilidad a la enfermedad, pero no es una causa única."],terms:"стрессовая реакция · stress response; аллостаз · allostasis",question:"¿Qué factores de estrés exigen actuar ahora y cuáles existen sobre todo en mis pensamientos?"},
      {number:2,title:"Glándulas, piel de gallina y hormonas",summary:"El cerebro coordina el estrés mediante el sistema nervioso autónomo y los ejes hormonales: una vía rápida con adrenalina y otra más lenta a través del eje HHA y los glucocorticoides.",points:["El sistema simpático moviliza; el parasimpático favorece la recuperación.","La adrenalina actúa rápido y los glucocorticoides prolongan la respuesta.","Una respuesta sana debe poder activarse y también detenerse."],terms:"ВНС · autonomic nervous system; ось HPA · HPA axis",question:"¿Qué ayuda a mi organismo a reconocer que el peligro ha terminado?"},
      {number:3,title:"Ictus, infartos y muerte vudú",summary:"El estrés aumenta el trabajo del corazón y la presión arterial. Cuando esta respuesta se repite continuamente, la adaptación se convierte en una carga cardiovascular.",points:["La hipertensión crónica daña las paredes vasculares.","La inflamación y la aterosclerosis aparecen con mayor facilidad en zonas dañadas.","El estrés interactúa con otros factores de riesgo."],terms:"гипертония · hypertension; атеросклероз · atherosclerosis",question:"¿Qué hábitos ayudan a mi cuerpo a completar la respuesta de estrés?"},
      {number:4,title:"Estrés, metabolismo y liquidación de activos",summary:"Ante una amenaza, el organismo libera glucosa y ácidos grasos para actuar de inmediato. Si ocurre de forma crónica, la movilización constante de energía tiene un coste metabólico.",points:["Las reservas se consumen en vez de destinarse a reparación.","Los picos hormonales frecuentes pueden reducir la sensibilidad a la insulina.","El estrés puede reducir el apetito o aumentar el deseo de alimentos calóricos."],terms:"глюкокортикоиды · glucocorticoids; инсулинорезистентность · insulin resistance",question:"Después del estrés, ¿como por hambre, cansancio o necesidad de consuelo?"},
      {number:5,title:"Úlceras, intestino y postres",summary:"El estrés modifica la motilidad, la secreción y el flujo sanguíneo digestivo. No explica por sí solo las enfermedades gastrointestinales, pero puede aumentar la vulnerabilidad y los síntomas.",points:["Durante una amenaza, la digestión deja de ser prioritaria.","Helicobacter pylori es importante en muchas úlceras.","El eje intestino-cerebro hace que los síntomas sean sensibles al contexto."],terms:"ось мозг–кишечник · gut–brain axis; функциональное расстройство · functional disorder",question:"¿Qué situaciones intensifican mis síntomas y qué cambia cuando me siento segura?"},
      {number:6,title:"Enanismo y la importancia de las madres",summary:"El crecimiento es un proyecto a largo plazo. Bajo una amenaza prolongada, la energía se destina a sobrevivir y el estrés temprano puede afectar al desarrollo.",points:["Las hormonas del estrés pueden frenar procesos ligados al crecimiento.","La nutrición, el cuidado y la seguridad emocional son relevantes.","La experiencia temprana influye, pero no determina el destino."],terms:"гормон роста · growth hormone; ранний стресс · early-life stress",question:"¿Qué condiciones permiten no solo sobrevivir, sino crecer?"},
      {number:7,title:"Sexo y reproducción",summary:"La reproducción requiere energía y una seguridad relativa. El estrés prolongado puede alterar la regulación hormonal, la libido y la fertilidad.",points:["El estrés puede inhibir las señales que regulan el eje reproductivo.","Los efectos dependen de la duración, intensidad y contexto individual.","Las expectativas y las relaciones interactúan con la fisiología."],terms:"репродуктивная ось · reproductive axis; либидо · libido",question:"¿Cómo modifican la seguridad, la intimidad y el control la respuesta corporal al estrés?"},
      {number:8,title:"Inmunidad, estrés y enfermedad",summary:"El vínculo no se reduce a «el estrés baja las defensas». Una reacción breve puede movilizarlas; el estrés crónico puede desregularlas y mantener la inflamación.",points:["La respuesta inmunitaria cambia con el tiempo.","El estrés crónico puede dificultar la cicatrización y el control inflamatorio.","La enfermedad surge de la interacción entre estrés, biología, conducta y ambiente."],terms:"психонейроиммунология · psychoneuroimmunology; воспаление · inflammation",question:"¿Por qué es más preciso decir que el estrés altera la regulación inmunitaria?"}
    ]
  },
  en: {
    eyebrow:"BOOK CLUB · ROBERT SAPOLSKY",title:"Why Zebras Don’t Get Ulcers",subtitle:"The psychology and physiology of stress, chapter by chapter",intro:"This section connects Sapolsky’s ideas with psychobiology: from the rapid fight-or-flight response to the effects of chronic stress on the heart, metabolism, digestion, growth, reproduction and immunity.",chaptersLabel:"Available chapters · 1–8",keyIdeas:"Key ideas",termsLabel:"Terms · RU · ES",questionLabel:"Question for reflection",fullTextLabel:"Full chapter summary",note:"Original Sensus Vitae study notes. This summary is not a substitute for the book or for medical advice.",
    chapters: [
      {number:1,title:"Why Don’t Zebras Get Ulcers?",summary:"The acute stress response can save us from an immediate threat. In humans, the same mechanism can be activated by thoughts, expectations and conflicts—and remain active for too long.",points:["Energy is rapidly directed towards muscles, heart and brain.","Digestion, growth, repair and reproduction are postponed.","Chronic activation raises vulnerability to disease but is not a single cause."],terms:"стрессовая реакция · respuesta de estrés; аллостаз · alostasis",question:"Which of my stressors require action now, and which mainly exist in thought?"},
      {number:2,title:"Glands, Gooseflesh, and Hormones",summary:"The brain coordinates stress through the autonomic nervous system and hormonal axes: a fast adrenaline pathway and a slower HPA-axis glucocorticoid pathway.",points:["The sympathetic system mobilises; the parasympathetic system supports recovery.","Adrenaline acts quickly; glucocorticoids sustain the response.","A healthy response must switch off as well as switch on."],terms:"ВНС · sistema nervioso autónomo; ось HPA · eje HHA",question:"What helps my body recognise that the danger has ended?"},
      {number:3,title:"Stroke, Heart Attacks, and Voodoo Death",summary:"Stress increases cardiac work and blood pressure. When repeated continuously, an adaptive response becomes a burden on the cardiovascular system.",points:["Chronic high blood pressure damages vessel walls.","Inflammation and atherosclerosis develop more easily at damaged sites.","Stress interacts with other risk factors rather than acting alone."],terms:"гипертония · hipertensión; атеросклероз · aterosclerosis",question:"Which regular habits help my body complete its stress response?"},
      {number:4,title:"Stress, Metabolism, and Liquidating Your Assets",summary:"During threat, the body releases glucose and fatty acids for immediate action. When this becomes chronic, constant energy mobilisation carries a metabolic cost.",points:["Energy stores are broken down instead of used for repair.","Frequent hormonal surges can reduce insulin sensitivity.","Stress can suppress appetite or increase cravings for calorie-dense food."],terms:"глюкокортикоиды · glucocorticoides; инсулинорезистентность · resistencia a la insulina",question:"After stress, am I eating from hunger, fatigue or a need for comfort?"},
      {number:5,title:"Ulcers, the Runs, and Hot Fudge Sundaes",summary:"Stress changes digestive motility, secretion and blood flow. It does not explain every gastrointestinal disorder, but it can amplify vulnerability and symptoms.",points:["Digestion loses priority during threat.","Helicobacter pylori is central to many ulcers.","The gut–brain axis makes symptoms sensitive to context."],terms:"ось мозг–кишечник · eje intestino-cerebro; функциональное расстройство · trastorno funcional",question:"Which situations intensify symptoms, and what changes when I feel safe?"},
      {number:6,title:"Dwarfism and the Importance of Mothers",summary:"Growth is a long-term project. Under prolonged threat, energy shifts towards survival, and early-life stress can influence development.",points:["Stress hormones can suppress growth-related processes.","Nutrition, care and emotional safety all matter.","Early experience influences sensitivity but does not dictate destiny."],terms:"гормон роста · hormona del crecimiento; ранний стресс · estrés temprano",question:"What conditions allow a person not merely to survive, but to grow?"},
      {number:7,title:"Sex and Reproduction",summary:"Reproduction requires energy and relative safety. Prolonged stress can disturb hormonal regulation, libido and fertility.",points:["Stress can inhibit signals controlling the reproductive axis.","Effects depend on duration, intensity and individual context.","Expectations and relationships interact with physiology."],terms:"репродуктивная ось · eje reproductivo; либидо · libido",question:"How do safety, intimacy and control change the body’s stress response?"},
      {number:8,title:"Immunity, Stress, and Disease",summary:"The relationship is more complex than “stress weakens immunity”. A brief response may mobilise defence, while chronic stress can disrupt regulation and sustain inflammation.",points:["The immune response changes over time.","Chronic stress can impair healing and inflammatory control.","Disease risk reflects stress, biology, behaviour and environment together."],terms:"психонейроиммунология · psiconeuroinmunología; воспаление · inflamación",question:"Why is it more accurate to say that stress alters immune regulation?"}
    ]
  },
  nl: {
    eyebrow:"BOEKENCLUB · ROBERT SAPOLSKY",title:"Waarom krijgen zebra’s geen maagzweren?",subtitle:"De psychologie en fysiologie van stress, hoofdstuk voor hoofdstuk",intro:"Dit onderdeel verbindt Sapolsky’s ideeën met de psychobiologie: van de snelle vecht-of-vluchtreactie tot de invloed van chronische stress op hart, stofwisseling, spijsvertering, groei, voortplanting en immuniteit.",chaptersLabel:"Beschikbare hoofdstukken · 1–8",keyIdeas:"Kernideeën",termsLabel:"Termen · RU · ES · EN",questionLabel:"Vraag ter overweging",fullTextLabel:"Volledige hoofdstuksamenvatting",note:"Originele studienotities van Sensus Vitae. Deze samenvatting vervangt het boek of medisch advies niet.",
    chapters: [
      {number:1,title:"Waarom krijgen zebra’s geen maagzweren?",summary:"De acute stressreactie kan bij direct gevaar levensreddend zijn. Bij mensen kan hetzelfde mechanisme door gedachten, verwachtingen en conflicten worden geactiveerd en te lang actief blijven.",points:["Energie gaat snel naar spieren, hart en hersenen.","Spijsvertering, groei, herstel en voortplanting worden uitgesteld.","Chronische activatie verhoogt kwetsbaarheid, maar is niet één enkele ziekteoorzaak."],terms:"стрессовая реакция · respuesta de estrés · stress response; аллостаз · alostasis · allostasis",question:"Welke stressoren vragen nu om actie en welke bestaan vooral in mijn gedachten?"},
      {number:2,title:"Klieren, kippenvel en hormonen",summary:"De hersenen coördineren stress via het autonome zenuwstelsel en hormonale assen: een snelle adrenalineroute en een tragere route via de HPA-as en glucocorticoïden.",points:["Het sympathische stelsel mobiliseert; het parasympathische bevordert herstel.","Adrenaline werkt snel, glucocorticoïden houden de reactie langer gaande.","Een gezonde reactie moet ook tijdig kunnen stoppen."],terms:"ВНС · sistema nervioso autónomo · autonomic nervous system; ось HPA · eje HHA · HPA axis",question:"Wat helpt mijn lichaam herkennen dat het gevaar voorbij is?"},
      {number:3,title:"Beroertes, hartaanvallen en voodoodood",summary:"Stress verhoogt hartarbeid en bloeddruk. Bij voortdurende herhaling wordt een aanpassing een belasting voor hart en bloedvaten.",points:["Chronische hoge bloeddruk beschadigt vaatwanden.","Ontsteking en atherosclerose ontstaan gemakkelijker op beschadigde plekken.","Stress werkt samen met andere risicofactoren."],terms:"гипертония · hipertensión · hypertension; атеросклероз · aterosclerosis · atherosclerosis",question:"Welke gewoonten helpen mijn lichaam de stressreactie af te ronden?"},
      {number:4,title:"Stress, stofwisseling en het liquideren van je bezittingen",summary:"Bij gevaar maakt het lichaam glucose en vetzuren vrij voor directe actie. Als dit chronisch gebeurt, heeft voortdurende energiemobilisatie een metabole prijs.",points:["Voorraden worden afgebroken in plaats van voor herstel gebruikt.","Veel hormonale pieken kunnen insulinegevoeligheid verminderen.","Stress kan eetlust remmen of trek in calorierijk voedsel vergroten."],terms:"глюкокортикоиды · glucocorticoides · glucocorticoids; инсулинорезистентность · resistencia a la insulina · insulin resistance",question:"Eet ik na stress uit honger, vermoeidheid of behoefte aan troost?"},
      {number:5,title:"Maagzweren, darmen en desserts",summary:"Stress verandert darmbeweging, afscheiding en doorbloeding. Het verklaart niet alle maag-darmziekten, maar kan kwetsbaarheid en klachten versterken.",points:["Spijsvertering verliest prioriteit bij gevaar.","Helicobacter pylori speelt bij veel maagzweren een belangrijke rol.","De darm-hersenas maakt klachten gevoelig voor context."],terms:"ось мозг–кишечник · eje intestino-cerebro · gut–brain axis; функциональное расстройство · trastorno funcional · functional disorder",question:"Welke situaties versterken mijn klachten en wat verandert als ik mij veilig voel?"},
      {number:6,title:"Dwerggroei en het belang van moeders",summary:"Groei is een langetermijnproject. Bij langdurig gevaar gaat energie naar overleven en vroege stress kan de ontwikkeling beïnvloeden.",points:["Stresshormonen kunnen groeiprocessen remmen.","Voeding, zorg en emotionele veiligheid zijn belangrijk.","Vroege ervaringen beïnvloeden gevoeligheid, maar bepalen het lot niet."],terms:"гормон роста · hormona del crecimiento · growth hormone; ранний стресс · estrés temprano · early-life stress",question:"Welke omstandigheden maken niet alleen overleven, maar ook groeien mogelijk?"},
      {number:7,title:"Seks en voortplanting",summary:"Voortplanting vraagt energie en relatieve veiligheid. Langdurige stress kan hormoonregulatie, libido en vruchtbaarheid verstoren.",points:["Stress kan signalen van de voortplantingsas onderdrukken.","De effecten hangen af van duur, intensiteit en context.","Verwachtingen en relaties werken samen met fysiologie."],terms:"репродуктивная ось · eje reproductivo · reproductive axis; либидо · libido · libido",question:"Hoe veranderen veiligheid, intimiteit en controle de lichamelijke stressreactie?"},
      {number:8,title:"Immuniteit, stress en ziekte",summary:"De relatie is complexer dan “stress verlaagt de weerstand”. Korte stress kan afweer mobiliseren; chronische stress kan regulatie verstoren en ontsteking onderhouden.",points:["De immuunreactie verandert in de tijd.","Chronische stress kan wondgenezing en ontstekingscontrole verstoren.","Ziekterisico ontstaat uit stress, biologie, gedrag en omgeving samen."],terms:"психонейроиммунология · psiconeuroinmunología · psychoneuroimmunology; воспаление · inflamación · inflammation",question:"Waarom is ‘stress verandert immuunregulatie’ nauwkeuriger dan ‘stress verzwakt de afweer’?"}
    ]
  }
};
for (const lang of ["es", "en", "nl"] as const) {
  sapolskyContent[lang].chapters[0].fullText = chapterOneTranslations[lang];
}
for (const lang of ["ru", "es", "en", "nl"] as const) {
  sapolskyContent[lang].chaptersLabel = sapolskyContent[lang].chaptersLabel.replace("1–8", "1–18");
  sapolskyContent[lang].chapters.push(...additionalChapterCards[lang], ...finalChapterCards[lang]);
  for (const chapter of sapolskyContent[lang].chapters) {
    if (fullChapterSummaries[lang][chapter.number]) chapter.fullText = fullChapterSummaries[lang][chapter.number];
    if (moreChapterSummaries[lang][chapter.number]) chapter.fullText = moreChapterSummaries[lang][chapter.number];
    if (finalChapterSummaries[lang][chapter.number]) chapter.fullText = finalChapterSummaries[lang][chapter.number];
  }
}
