import { articleTranslations } from "./article-translations";
export const languages = ["ru", "es", "en", "nl"] as const;
export type Language = (typeof languages)[number];
export const isLanguage = (value: string): value is Language => languages.includes(value as Language);

export const ui = {
  ru: { nav:{home:"Главная",study:"Учёба",library:"Библиотека",club:"Клуб",about:"Обо мне"}, eyebrow:"ПСИХОЛОГИЯ · ФИЛОСОФИЯ · КРИТИЧЕСКОЕ МЫШЛЕНИЕ", title:"Понимать глубже. Думать яснее. Жить осознанно.", intro:"Понятные конспекты и объяснения по психологии — для студентов, любителей науки и участников Sensus Vitae.", explore:"Перейти к новым материалам", latest:"Новые учебные материалы", paths:"Выберите направление", pathIntro:"Начните с темы, которая вам сейчас ближе. Каждый раздел помогает увидеть связи между теорией, исследованиями и повседневной жизнью.", openPath:"Открыть раздел", valuePoints:["Сложные идеи — понятным языком","Психология на четырёх языках","Связи между наукой и жизнью"], read:"Читать материал", all:"Смотреть всю библиотеку", question:"Вопрос для размышления", questionText:"Меняет ли знание о причинах нашего поведения степень личной ответственности?", footer:"Знать · Думать · Развиваться · Жить осознанно" },
  es: { nav:{home:"Inicio",study:"Estudio",library:"Biblioteca",club:"Club",about:"Sobre mí"}, eyebrow:"PSICOLOGÍA · FILOSOFÍA · PENSAMIENTO CRÍTICO", title:"Comprender a fondo. Pensar con claridad. Vivir conscientemente.", intro:"Apuntes y explicaciones claras de psicología para estudiantes, personas interesadas en la ciencia y la comunidad Sensus Vitae.", explore:"Ver los nuevos materiales", latest:"Nuevos materiales de estudio", paths:"Elige un área", pathIntro:"Empieza por el tema que más te interese ahora. Cada área ayuda a conectar la teoría, la investigación y la vida cotidiana.", openPath:"Abrir sección", valuePoints:["Ideas complejas, explicadas con claridad","Psicología en cuatro idiomas","Conexiones entre ciencia y vida"], read:"Leer el material", all:"Ver toda la biblioteca", question:"Pregunta para reflexionar", questionText:"¿Conocer las causas de nuestra conducta cambia el grado de responsabilidad personal?", footer:"Saber · Pensar · Crecer · Vivir conscientemente" },
  en: { nav:{home:"Home",study:"Study",library:"Library",club:"Club",about:"About"}, eyebrow:"PSYCHOLOGY · PHILOSOPHY · CRITICAL THINKING", title:"Understand deeply. Think clearly. Live consciously.", intro:"Clear psychology notes and explanations for students, curious minds and the Sensus Vitae community.", explore:"See the latest materials", latest:"Latest study materials", paths:"Choose a learning path", pathIntro:"Start with the subject that speaks to you now. Each path connects theory, research and everyday life.", openPath:"Open section", valuePoints:["Complex ideas, clearly explained","Psychology in four languages","Connections between science and life"], read:"Read the material", all:"Explore the full library", question:"Question for reflection", questionText:"Does knowing the causes of our behaviour change the degree of personal responsibility?", footer:"Know · Think · Grow · Live consciously" },
  nl: { nav:{home:"Start",study:"Studie",library:"Bibliotheek",club:"Club",about:"Over mij"}, eyebrow:"PSYCHOLOGIE · FILOSOFIE · KRITISCH DENKEN", title:"Dieper begrijpen. Helder denken. Bewust leven.", intro:"Heldere notities en uitleg over psychologie voor studenten, nieuwsgierige lezers en de Sensus Vitae-gemeenschap.", explore:"Bekijk de nieuwste materialen", latest:"Nieuwe studiematerialen", paths:"Kies een leerroute", pathIntro:"Begin met het onderwerp dat je nu het meest aanspreekt. Elke route verbindt theorie, onderzoek en het dagelijks leven.", openPath:"Open onderdeel", valuePoints:["Complexe ideeën helder uitgelegd","Psychologie in vier talen","Verbindingen tussen wetenschap en leven"], read:"Lees het materiaal", all:"Bekijk de hele bibliotheek", question:"Vraag ter overweging", questionText:"Verandert kennis over de oorzaken van ons gedrag de mate van persoonlijke verantwoordelijkheid?", footer:"Weten · Denken · Groeien · Bewust leven" },
} as const;

export const categories = {
  ru: [["Психобиология","Мозг, нейроны, генетика и поведение"],["Анализ данных","Статистика простым и точным языком"],["Методы исследования","Как психология получает надёжные знания"],["Мотивация","Почему мы начинаем, выбираем и продолжаем"],["Социальная психология","Как люди влияют друг на друга"],["История психологии","Развитие психологических идей, школ и научных подходов"]],
  es: [["Psicobiología","Cerebro, neuronas, genética y conducta"],["Análisis de datos","Estadística explicada con claridad y precisión"],["Métodos de investigación","Cómo obtiene la psicología conocimientos fiables"],["Motivación","Por qué empezamos, elegimos y perseveramos"],["Psicología social","Cómo influyen las personas unas en otras"],["Historia de la psicología","El desarrollo de las ideas, escuelas y enfoques científicos de la psicología"]],
  en: [["Psychobiology","Brain, neurons, genetics and behaviour"],["Data analysis","Statistics in clear, precise language"],["Research methods","How psychology builds reliable knowledge"],["Motivation","Why we begin, choose and persist"],["Social psychology","How people influence one another"],["History of psychology","The development of psychological ideas, schools and scientific approaches"]],
  nl: [["Psychobiologie","Hersenen, neuronen, genetica en gedrag"],["Data-analyse","Statistiek in heldere, precieze taal"],["Onderzoeksmethoden","Hoe psychologie betrouwbare kennis opbouwt"],["Motivatie","Waarom we beginnen, kiezen en volhouden"],["Sociale psychologie","Hoe mensen elkaar beïnvloeden"],["Geschiedenis van de psychologie","De ontwikkeling van psychologische ideeën, stromingen en wetenschappelijke benaderingen"]],
} as const;

export type StaticArticle={slug:string;lang:Language;category:string;title:string;summary:string;readTime:string;body:{heading?:string;paragraphs?:string[];bullets?:string[]}[];source?:{label:string;href:string}};
const originalArticles:StaticArticle[]=[
 {slug:"personality-genetics-nature-2026",lang:"ru",category:"Генетика и поведение",readTime:"7 мин",title:"Генетика личности: огромная выборка, но не «гены характера»",summary:"Крупнейший GWAS по чертам Большой пятёрки помогает увидеть полигенную архитектуру личности — и одновременно показывает границы генетических предсказаний.",body:[{paragraphs:["2 сентября 2026 года журнал Nature опубликовал крупнейший на сегодняшний день метаанализ генетических ассоциаций с личностью. Исследователи объединили данные 46 когорт: в зависимости от черты выборка составляла от 611 тысяч до 1,14 миллиона человек.","Авторы изучали пять широких черт модели Big Five: экстраверсию, доброжелательность, добросовестность, нейротизм и открытость опыту. GWAS выявил 1 260 статистически значимых ведущих генетических вариантов; 824 из них находились в локусах, ранее не связанных с соответствующей чертой личности."]},{heading:"Как это понимать",paragraphs:["Личность полигенна: различия между людьми связаны не с одним или несколькими «генами характера», а с совокупным вкладом множества генетических вариантов, биологических процессов и среды. Эффект каждого отдельного варианта чрезвычайно мал. Поэтому найденная ассоциация описывает статистическую закономерность на уровне больших групп, а не судьбу отдельного человека."]},{heading:"Что это НЕ означает",bullets:["GWAS не позволяет надёжно предсказывать характер конкретного человека.","Исследование не доказывает генетический детерминизм: генетическая предрасположенность не равна неизменной личности.","Ассоциация варианта с чертой не означает, что этот вариант сам по себе напрямую вызывает определённое поведение."]},{heading:"Ограничения",bullets:["Основная статистическая мощность исследования получена из выборок преимущественно европейского происхождения; переносимость результатов на другие популяции остаётся ограниченной.","Оценки личности зависят от опросников, самоотчётов, используемого инструмента и того, кто оценивает человека.","Исследование не было предварительно зарегистрировано (not preregistered), поэтому подтверждающие и поисковые анализы не всегда можно строго разделить."]},{heading:"Мысль для размышления",paragraphs:["Если биология влияет на наши предрасположенности, но не определяет личность полностью, где проходит граница между тем, что нам дано, и тем, что мы способны изменить опытом, средой и собственными решениями?"]}],source:{label:"Schwaba T. et al., “Robust inference and correlates from genetic associations with personality”, Nature, 2026. DOI: 10.1038/s41586-026-10992-9",href:"https://doi.org/10.1038/s41586-026-10992-9"}},
 {slug:"neuron-and-glia",lang:"ru",category:"Психобиология",readTime:"6 мин",title:"Нейрон и глия: не одинокая клетка, а живая система",summary:"Почему мозг нельзя понять, изучая только нейроны, и какую работу выполняют разные типы глиальных клеток.",body:[{paragraphs:["Нейрон специализируется на приёме, обработке и передаче сигналов. Но он не работает изолированно: его питание, защита, химическая среда и скорость проведения импульса зависят от глиальных клеток."]},{heading:"Четыре важные роли глии",bullets:["Астроциты поддерживают химическое равновесие и участвуют в работе синапсов.","Олигодендроциты в ЦНС и клетки Шванна в ПНС образуют миелин.","Микроглия выполняет иммунный надзор и удаляет повреждённые элементы.","Эпендимные клетки связаны с циркуляцией спинномозговой жидкости."]},{heading:"Главная идея",paragraphs:["Мозг — не проводка из нейронов, а динамическая экосистема. Поведение возникает из взаимодействия клеток, молекул, опыта и среды."]}]},
 {slug:"mean-and-standard-deviation",lang:"ru",category:"Анализ данных",readTime:"7 мин",title:"Среднее и стандартное отклонение: центр и разброс",summary:"Как две величины вместе описывают данные и почему стандартное отклонение нельзя читать отдельно от среднего.",body:[{paragraphs:["Среднее арифметическое показывает условный центр набора данных. Оно отвечает на вопрос: вокруг какого значения в среднем располагаются наблюдения?"]},{heading:"Что добавляет стандартное отклонение",paragraphs:["Стандартное отклонение показывает типичное расстояние наблюдений от среднего. Малое значение означает концентрацию данных, большое — заметный разброс."],bullets:["Среднее без разброса может скрыть различия между группами.","Знак отклонения исчезает после возведения в квадрат.","Для выборочной оценки дисперсии часто используется деление на n − 1."]}]},
 {slug:"stress-and-personality",lang:"ru",category:"Психология и жизнь",readTime:"8 мин",title:"Стресс проходит через фильтр личности",summary:"Почему одинаковая ситуация становится угрозой для одного человека и задачей — для другого.",body:[{paragraphs:["Стрессовая реакция определяется не только событием. Важны оценка ситуации, чувство контроля, предсказуемость, социальная поддержка и привычный способ интерпретации намерений других людей."]},{heading:"Не только характер",bullets:["Темперамент влияет на чувствительность к стимулам.","Опыт формирует ожидания и стратегии совладания.","Социальная среда способна усиливать или смягчать физиологическую реакцию."]},{heading:"Практический вывод",paragraphs:["Работа со стрессом — это не требование «думать позитивно». Это расширение контроля, уточнение интерпретаций и создание поддерживающей среды."]}]},
 {slug:"neuron-and-glia",lang:"en",category:"Psychobiology",readTime:"6 min",title:"Neuron and glia: a living system, not a solitary cell",summary:"Why the brain cannot be understood through neurons alone, and what glial cells contribute.",body:[{paragraphs:["Neurons receive, process and transmit signals, but their nutrition, protection, chemical environment and conduction speed depend on glial cells."]},{heading:"The central idea",bullets:["Astrocytes support chemical balance and synapses.","Oligodendrocytes and Schwann cells form myelin.","Microglia provide immune surveillance."],paragraphs:["The brain is a dynamic ecosystem shaped by cells, molecules, experience and environment."]}]},
 {slug:"neuron-and-glia",lang:"nl",category:"Psychobiologie",readTime:"6 min",title:"Neuron en glia: een levend systeem, geen eenzame cel",summary:"Waarom we de hersenen niet via neuronen alleen kunnen begrijpen, en wat gliacellen bijdragen.",body:[{paragraphs:["Neuronen ontvangen, verwerken en verzenden signalen, maar hun voeding, bescherming, chemische omgeving en geleidingssnelheid hangen af van gliacellen."]},{heading:"De hoofdgedachte",bullets:["Astrocyten ondersteunen het chemisch evenwicht en synapsen.","Oligodendrocyten en Schwann-cellen vormen myeline.","Microglia verzorgen immuunbewaking."],paragraphs:["De hersenen zijn een dynamisch ecosysteem dat wordt gevormd door cellen, moleculen, ervaring en omgeving."]}]},
 {slug:"neuron-and-glia",lang:"es",category:"Psicobiología",readTime:"6 min",title:"Neurona y glía: un sistema vivo, no una célula aislada",summary:"Por qué no podemos comprender el cerebro estudiando solo las neuronas y qué funciones cumplen las células gliales.",body:[{paragraphs:["Las neuronas se especializan en recibir, procesar y transmitir señales. Sin embargo, su nutrición, protección, entorno químico y velocidad de conducción dependen de las células gliales."]},{heading:"Cuatro funciones importantes de la glía",bullets:["Los astrocitos mantienen el equilibrio químico y participan en el funcionamiento de las sinapsis.","Los oligodendrocitos en el SNC y las células de Schwann en el SNP forman la mielina.","La microglía realiza la vigilancia inmunitaria y elimina elementos dañados.","Las células ependimarias participan en la circulación del líquido cefalorraquídeo."]},{heading:"Idea principal",paragraphs:["El cerebro no es un simple cableado de neuronas, sino un ecosistema dinámico. La conducta surge de la interacción entre células, moléculas, experiencia y ambiente."]}]},
 {slug:"mean-and-standard-deviation",lang:"es",category:"Análisis de datos",readTime:"7 min",title:"Media y desviación típica: centro y dispersión",summary:"Cómo dos medidas describen conjuntamente los datos y por qué la desviación típica no debe interpretarse sin la media.",body:[{paragraphs:["La media aritmética indica el centro aproximado de un conjunto de datos. Responde a la pregunta: ¿alrededor de qué valor se sitúan, por término medio, las observaciones?"]},{heading:"Qué aporta la desviación típica",paragraphs:["La desviación típica muestra la distancia habitual de las observaciones respecto a la media. Un valor pequeño indica concentración; uno grande, una dispersión apreciable."],bullets:["La media sin una medida de dispersión puede ocultar diferencias entre grupos.","El signo de las desviaciones desaparece al elevarlas al cuadrado.","Para estimar la varianza muestral suele dividirse entre n − 1."]}]},
 {slug:"stress-and-personality",lang:"es",category:"Psicología y vida",readTime:"8 min",title:"El estrés pasa por el filtro de la personalidad",summary:"Por qué una misma situación puede convertirse en una amenaza para una persona y en un reto para otra.",body:[{paragraphs:["La respuesta de estrés no depende únicamente del acontecimiento. También importan la evaluación de la situación, la sensación de control, la previsibilidad, el apoyo social y la forma habitual de interpretar las intenciones ajenas."]},{heading:"No es solo cuestión de carácter",bullets:["El temperamento influye en la sensibilidad a los estímulos.","La experiencia configura expectativas y estrategias de afrontamiento.","El entorno social puede intensificar o amortiguar la respuesta fisiológica."]},{heading:"Conclusión práctica",paragraphs:["Trabajar con el estrés no significa obligarse a «pensar en positivo». Significa ampliar el control, revisar las interpretaciones y crear un entorno de apoyo."]}]},
];
export const staticArticles: StaticArticle[] = languages.flatMap(lang =>
  originalArticles.filter(a => a.lang === "ru").map(original => {
    const article = articleTranslations.find(a => a.lang === lang && a.slug === original.slug)
      ?? originalArticles.find(a => a.lang === lang && a.slug === original.slug);
    if (!article) throw new Error(`Missing translation: ${lang}/${original.slug}`);
    return article;
  })
);
